Cy create language
umbraco/Umbraco-CMS pull request #11546
Opened 2021-10-29 18:40 UTC by jemayn

Remaking https://github.com/umbraco/Umbraco-CMS/pull/11307 to get around a GH bug that showed way more changes.

@madsrasmussen If I add the TS definitions like they are in tests/Umbraco.Tests.AcceptanceTest/cypress/typings.d.ts I get intellisense and it all works 🙂

We could use that alongside adding the commands to the commands.js file we get typed custom commands, which can then once in a while be pulled into @bergmania 's package.

2021-10-30 07:02 UTC, Zeegaan requested changes
Found a few things that needs changing 👍

2021-10-30 07:02 UTC, Zeegaan commented on tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Languages/languages.ts
> +      cy.umbracoEnsureLanguageNotExists(culture);
```suggestion
      cy.umbracoEnsureLanguageNameNotExists(culture);
```
Use the already existing language method

2021-10-30 07:02 UTC, Zeegaan commented on tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Languages/languages.ts
>          cy.umbracoEnsureLanguageNotExists(language2);
```suggestion
        cy.umbracoEnsureLanguageNameNotExists(language1);
        cy.umbracoEnsureLanguageNameNotExists(language2);
```

2021-10-30 07:02 UTC, Zeegaan commented on tests/Umbraco.Tests.AcceptanceTest/cypress/typings.d.ts
> +            umbracoEnsureLanguageNotExists: (name: string) => Chainable<void>;
As mentioned in your other PR we already have a method called cy.umbracoEnsureLanguageNameNotExists(name)
```suggestion
    namespace Cypress {
        interface Chainable<Subject> {
```

2021-11-03 20:37 UTC, jemayn commented
@Zeegaan 

The existing command matches on the language name, not the culture like this one. I've updated the method on this PR to make it clearer that it's on culture 🙂

2021-11-04 09:38 UTC, elit0451 commented
Just FYI: The just merged PR https://github.com/umbraco/Umbraco-CMS/pull/11527 already moved the **languages.ts** to the `tests` folder, instead of `src`. 🙂 
So make sure to get the latest changes from `umbraco:v9/contrib`.

2021-11-12 19:44 UTC, mikecp commented
Hello @jemayn ,

Thanks for this PR, it's a nice addition to the acceptance tests suite 😉👍

It all works good, but before merging, I wanted to check with you, in the line of @Zeegaan 's remarks earlier, if there was a specific reason why you needed to add the method  `umbracoEnsureLanguageCultureNotExists` and could not use the existing one `umbracoEnsureLanguageNameNotExists`.

I just want to make sure that we do not create what seems to be an "almost duplicate" method if there is no specific reason, but maybe I am overseeing something. 😁

Thanks in advance for your feedback!

2021-11-13 19:26 UTC, jemayn commented
> Hello @jemayn ,
> 
> Thanks for this PR, it's a nice addition to the acceptance tests suite 😉👍
> 
> It all works good, but before merging, I wanted to check with you, in the line of @Zeegaan 's remarks earlier, if there was a specific reason why you needed to add the method `umbracoEnsureLanguageCultureNotExists` and could not use the existing one `umbracoEnsureLanguageNameNotExists`.
> 
> I just want to make sure that we do not create what seems to be an "almost duplicate" method if there is no specific reason, but maybe I am overseeing something. 😁
> 
> Thanks in advance for your feedback!

Hey @mikecp !

I can amend the PR to use the existing method if you want, but I felt this was a better method than the existing one - the existing one relies on the language names which can be anything, this method uses the culture which is still just a string - but feels a bit safer to use..

2021-11-14 01:19 UTC, mikecp commented
Hi @jemayn ,

Thanks for clearing the difference out, looking on a culture name seems indeed safer, so let's keep that method in there 😉!

2021-11-14 01:19 UTC, mikecp approved these changes

2021-11-14 01:20 UTC, merged