change LogDto Comment and Parameters to nvarcharmax
umbraco/Umbraco-CMS pull request #11578
Opened 2021-11-04 19:16 UTC by LottePitcher

### Prerequisites

- [X] I have added steps to test this contribution in the description below

This fixes issue https://github.com/umbraco/Umbraco-CMS/issues/9458

### Description

This pull request is a result of a Discord Hack session earlier today with Seb, Warren and some other community folk.

To replicate the issue you would need to have say 40+ languages configured in your back office, and then try to save or publish all variants *in one go*.  This causes a SQL error, which therefore prevents the node being saved/published.  This is because Umbraco is trying to write a record to the `UmbracoLogs` table with a comma delimited list of the affected variants in the `parameters` column, and that column has a max length of only 500 chars.

We checked where the 'parameters' column is used. Turns out it's displayed on the 'info' tab as indicated in this screenshot:

![image](https://user-images.githubusercontent.com/4716542/140396247-32d16908-3232-49ec-9733-4d0d80f527c2.png)

We discussed truncating the string to 500 characters before saving but this would mean that there was missing information on the info tab, and it is important to know who published which variant.

We discussed that having such a long list of language names isn't ideal, especially as the language list is hard-coded to the English name. But those enhancements would need proper discussion, so we agreed to keep the scope of this PR to be just fixing the issue that is preventing people from saving content (which does actually happen when you use a tool such as uSync or Translation Manager to create this many variants in one go!).

People who have hit this problem already may have increased the size of the column on the database themselves, so we set the string to be `nvarchar(max)` as this wouldn't cause those people any truncation issues during an upgrade.  

We also thought it was a good idea to change the `logComment` column at the same time to be nvarchar(max) as its existing length of 4000 felt rather arbitrary.

Once the database column has been increased in size you are then able to save/publish 40+ variants in one go. This was shown on the Discord session earlier today.

As this commit contains database schema changes, this PR has been tested on:

- A fresh install using SQL db
- An upgrade of existing instance using SQL db
- A fresh install using SQL CE db
- An upgrade of existing instance using SQL CE db

In all tests above the database gets created / updated correctly.  

Oh and @nul800sebastiaan said to add the migration to a folder called 'V_8_18_0', so I did 😉

2021-11-05 09:17 UTC, mikecp commented
Hi @LottePitcher , thanks for the PR, with max 2Gb those fields should indeed be long enough now 😅😁

I noticed that one of the data persistence tests failed, I'll run them again just to make sure, but if it remains, it might be worth investigating if it's due to this change.

Cheers!

2021-11-05 10:03 UTC, LottePitcher commented
Thanks @mikecp 

`System.Data.SqlServerCe.SqlCeException : The ntext and image data types cannot be used in WHERE, HAVING, GROUP BY, ON, or IN clauses, except when these data types are used with the LIKE or IS NULL predicates.`

Considering this PR introduced an nvarchar(max), which I believe is ntext in SQL CE, it does sound like it is the culprit! 

Sounds like further investigation is required 😢.  But yay for tests 😂

2021-11-05 10:48 UTC, mikecp commented
Yes I saw the ntext issue in the log too, and indeed feared that this would be the CE interpretation for nvarchar(max) 😥
But it's indeed good that we have tests to tackle this before it goes live 😅

2021-11-05 10:50 UTC, mikecp requested changes
Code changes look all good but some further investigation is needed about the failing test(s).

2021-11-06 02:36 UTC, nzdev commented
Have a look at https://github.com/umbraco/Umbraco-CMS/pull/11014/files  for how to work around SQLCE. That pr fixes the rest of the ntext columns

2021-11-11 14:34 UTC, p-m-j commented
During lunch hack today we looked into whether we can update ExpressionVisitorBase.cs to write the operand as 'like' as opposed to = for SqlCe when a where clause is checking against a ntext column.

We proved this works by always using like as opposed to = but the code needs to be more context aware.

2022-02-22 20:29 UTC, closed without merging