Added dictionary filter by name
umbraco/Umbraco-CMS pull request #12765
Opened 2022-08-01 22:40 UTC by Lantzify

### Description

Just added a simple `umb-search-filter` in order to better find dictionary items when they start to pile up.

2022-08-02 23:05 UTC, mikecp requested changes
Hi @Lantzify ,

Thanks a lot for this new nice addition to the dictionary section 👍
I just added a few comments regarding localization, if you could have a look at them and update the PR, it would be just great 😁
Cheers!

2022-08-03 09:35 UTC, Lantzify commented on src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
> +    <key alias="noItemsFound">There were no dictionary items found.</key>
Absolutely! Missed that one 😅

2022-08-03 09:39 UTC, Lantzify commented on src/Umbraco.Web.UI.Client/src/views/dictionary/list.html
> +                                 text="Type to filter...">
Isn't it already localized? I changed the backoffice langue to Swedish. 🤔
![Capture](https://user-images.githubusercontent.com/20320733/182576773-8afe4791-cc7a-49d5-a4ed-cfff0d3cd18c.PNG)

2022-08-07 21:57 UTC, mikecp commented on src/Umbraco.Web.UI.Client/src/views/dictionary/list.html
> +                                 text="Type to filter...">
Indeed, I did not pay attention to the `label-key` attribute 😅

2022-08-07 22:34 UTC, mikecp commented
Hi @Lantzify ,

Thanks for the update, I've tested and all works fine 👍🎉
I just have a last concern about the "order by name" part after the filter. In the current situation, the items in the table are displayed in the same order as in the dictionary structure:

![image](https://user-images.githubusercontent.com/1769475/183313123-529bbb11-86ea-49f9-a328-70ffce176d0f.png)

With the "order by name", they are displayed alphabetically as expected :

![image](https://user-images.githubusercontent.com/1769475/183313224-a667bf56-cf05-487e-a120-8d51eb9e0d9a.png)

I think this might be confusing at first load and when the filter is left empty, because then it's kind of a change in behavior from previously (and I'm afraid it might even be seen as breaking change by HQ team), but I am also wondering whether having the ordering by name when the filter is filled in has any specific added value compared to keeping the items in original order.
What's your opinion about it? Maybe I am overseeing something?

Cheers!

2022-08-11 23:06 UTC, mikecp approved these changes

2022-08-11 23:12 UTC, mikecp commented
Hi @Lantzify ,

Thank you for the update, I think it is good to go and get merged now 👍😅
But it would be great indeed to have sort action to the dictionary, I guess this makes a new topic of PR for you 😁😉

Thanks again for all the love you put in the dictionary section, I think it has improved a lot in the last few months thanks to all your PR's 👍👍

Cheers and H5YR !!

2022-08-11 23:12 UTC, merged