Fixes #12972 for validating legacy member passwords
umbraco/Umbraco-CMS pull request #12973
Opened 2022-09-09 12:52 UTC by busrasengul

Umbraco has the `MemberPasswordHasher` which then calls `LegacyPasswordSecurity`.

This successfully validates the correct legacy password hash and returns true.

As it's a legacy password the `MemberPasswordHasher` returns `PasswordVerificationResult.SuccessRehashNeeded` which seems helpful because it allows you to perform different logic.

But `UmbracoUserManager` checks this method returns `PasswordVerificationResult.Success` to determine if the password is valid. Therefore it's always false for every legacy password.

The `MemberManager` should check both `Success` or `SuccessRehashNeeded` states when validating a password.

If this isn't suitable perhaps there should be a config that allows this check (off by default).

2022-09-18 12:33 UTC, mikecp requested changes
Hi @busrasengul ,
Thanks for spotting and solving this issue 👍
Since we are "just" validating credentials, it seems indeed legit to check on both success enum values at once.

I just have one question before merging: it seems that the "hash" variable on line 267 is not used further, so my guess is that we could get rid of it to save a useless call... What do you think?

2022-09-26 13:42 UTC, busrasengul commented
Thank you @mikecp 
This has been addressed now 👍

2022-09-26 22:36 UTC, mikecp approved these changes

2022-09-26 22:37 UTC, mikecp commented
Thanks @busrasengul for the update! It's all ready to be merged now 😃

2022-09-26 22:37 UTC, merged