New backoffice/add system text json configuration attribute
umbraco/Umbraco-CMS pull request #12998
Opened 2022-09-14 12:37 UTC by Zeegaan

# Notes
- Added new ManagementApiBaseController that all of the api in ManagementApi project should inherit from
- Created new EnumOutput formatter that now adds the JsonStringEnumConverter to our converts, so we serialize enum by text and not by number.
- Added new SystemTextJsonConfigurationAttribute, that now ensures our properties gets serialized by camelCase so we don't have to explictly set `JsonPropertyName("name")` on every property. and ofcourse also constaints the new EnumOutputFormatter

2022-09-16 12:45 UTC, kjac commented on src/Umbraco.Cms.ManagementApi/Controllers/MananagementApiBaseController.cs
> +public class MananagementApiBaseController : Controller
Suggest renaming to `MananagementApiControllerBase` to follow the general naming convention

2022-09-16 12:51 UTC, kjac commented on src/Umbraco.Cms.ManagementApi/Filters/EnumOutputFormatter.cs
> +public class EnumOutputFormatter : SystemTextJsonOutputFormatter
Suggest renaming to `ManagementApiJsonOutputFormatter` - we may end up doing more here than enum formatting.

2022-09-16 12:52 UTC, kjac commented on src/Umbraco.Cms.ManagementApi/Filters/SystemTextJsonConfigurationAttribute.cs
> +public class SystemTextJsonConfigurationAttribute : TypeFilterAttribute
Suggest renaming this to `ManagementApiJsonConfigurationAttribute`, to make it abundantly clear what it is used for.

2022-09-16 12:55 UTC, kjac requested changes
@Zeegaan the code works like a charm 😄 I have suggested some naming changes, have a look if you agree with them.

We must remember to apply this new base controller to all existing new-backoffice controllers. I will make a note of this 👍

2022-09-20 05:51 UTC, Zeegaan commented
Pipelines failing has to do with the dev branch failing, not the latest change 👍

2022-09-20 05:55 UTC, Zeegaan commented
@kjac I will go through and update the existing controllers in dev and in my PRs when this is merged aswell 🚀

2022-09-20 06:55 UTC, kjac approved these changes

2022-09-20 10:40 UTC, merged