Play01
umbraco/Umbraco-CMS pull request #13120
Opened 2022-10-05 07:57 UTC by gadgetfbi

### Prerequisites

https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/27

### Description
Moved the role and aria-selected from the buttons to the child listitem elements to conform with the expectation that tablist child elements have a role of tab. This change will apply to all of the section tab navigation items.

2022-10-05 07:58 UTC, gadgetfbi commented
n.b. the last 4 commits here are me trying to figure things out ;) - thanks!

2022-10-05 21:20 UTC, gadgetfbi commented
Hi Sebastiaan, thanks for looking at this.

The list items, _li.umb-tab--active_, are wrapped in <ul>'s so I assumed that perhaps the issue had been confused a little by the role of _tablist_ that has been assigned to the parent ul's. I don't see an issue with these child list items and nothing related is being flagged by Axe or Wave when running an a11y check.

I'll double check the list of accessibility issues and see if this one is actually on there.

Thanks,
Rob

2022-10-05 21:28 UTC, gadgetfbi commented
https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/26
https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/25

2022-10-21 14:56 UTC, glombek requested changes
Hi @gadgetfbi,

Thanks so much for your pull request.

I've just been looking into this and it functions fine (including with keyboard navigation and a screen reader). However, it does introduce us to another WCAG violation: https://dequeuniversity.com/rules/axe/4.4/nested-interactive

Although this is a lower severity than the current issue (critical to serious), it'd be nice to get this working without any WCAG issues.

I suspect the fix would be to not use a `ul` at all, and do something a little closer to the example here: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#example

This would, no doubt result in a little restyling to make it look as it does currently.

Let me know if you'd like any more elaboration.

Joe

2023-03-28 07:36 UTC, nul800sebastiaan commented
Since there's been no activity on this one for a while, let's get this one merged for now and it can be improved up later, I'll point to Joe's comment in the related issue. 

Thanks again @gadgetfbi and we'd love it if you have some time to further fix things even better according to Joe's comment! 🙏

2023-03-28 07:36 UTC, merged

2023-03-28 07:46 UTC, nul800sebastiaan commented
Cherry picked for 10.5 in 391bfb73e83f04275baf83ba380a8c8e14b58983