V10: 13125 don't return "null"
umbraco/Umbraco-CMS pull request #13163
Opened 2022-10-11 10:31 UTC by Zeegaan

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13125
# Notes
- Added null check to return null if parameter is null

# How to test
- Follow the detailed steps in issue 🙌

2022-10-17 13:36 UTC, elit0451 commented
Looks good, waiting for the pipelines' green light and will be merging 💪

2022-10-17 14:18 UTC, Zeegaan commented
I have pointed this for v11, as this is a big behavioral change, where we now convert `null` values to empty strings, instead of `null`, so this needs some testing.

## Note
This might be backported to v10 if found not to be an issue after the v11rc testing period 🙌

2022-10-18 06:40 UTC, elit0451 requested changes
Looks good, the only thing is that you missed the `return` 😅 without it the error is still there

2022-10-18 06:40 UTC, elit0451 commented on src/Umbraco.Core/PropertyEditors/DataValueEditor.cs
> +            Attempt.Succeed<object?>(null);
```suggestion
            return Attempt.Succeed<object?>(null);
```

2022-10-18 08:56 UTC, merged

2023-03-20 10:18 UTC, CarlSargunar commented
Hi @Zeegaan - do you know if this is likely to now be back-ported to 10 as mentioned in earlier comments?

2023-03-20 10:27 UTC, Zeegaan commented
Hi @CarlSargunar, I don't think we can, as this would be breaking. I know all bugs are on some level considered "behavioral breaking", but I could suspect someone relying on this behavior somewhere, and thus it would break their site 😅