Use `getLocalDate` from dateHelper
umbraco/Umbraco-CMS pull request #13469
Opened 2022-11-24 08:11 UTC by bjarnef

### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description

2022-11-24 13:37 UTC, bjarnef commented
@nielslyngsoe @iOvergaard it would be great to clean up this redundant JavaScript 😁

2022-11-24 17:10 UTC, nielslyngsoe commented
A thing to be aware about in this case is that this is public available so we cannot know if there is packages or other things that relies on this. So in that perspective it cannot be removed. If the functionality is exactly the same one might make one use the other, but we need to be sure of such. :-) I hope that perspective helps to why we have old code lying around. :-)

2022-11-24 19:00 UTC, bjarnef commented
@nielslyngsoe isn't is a private/local function in user controller? I wouldn't expect developers to be alle to call this function, but inject `dateHelper` or other services.

2022-11-28 09:10 UTC, iOvergaard requested changes
Hi @bjarnef, thanks for your discovery here. As @nielslyngsoe suggested, it might be used outside our own scope. A simple remediation would be just to make the function pass it on directly to `dateHelper` like 
```js
function getLocalDate(date, culture, format) {
    return dateHelper.getLocaleDate(date, culture, format);
}
```

And give it a jsdoc to mark it as obsolete and we'll try to figure out if we can remove it from the next major

2022-11-28 09:11 UTC, iOvergaard commented
NB! The build is failing because `dateHelper` was already present in the function and is now being imported twice.

2022-11-28 09:32 UTC, bjarnef commented
Hi @iOvergaard 

Okay, I am not sure in which use-case and if it is possible to call this function. I guess it would be kind of a hack as the services or helpers in general should be used.

Anyway I think in past many local functions have been removed/changed without being marked as breaking change.

2022-11-28 09:39 UTC, bjarnef commented
@iOvergaard I have updated the code to keep `getLocalDate()` function here.

2022-11-29 09:27 UTC, iOvergaard commented
Yes, that would be great, @bjarnef

2022-11-29 10:26 UTC, bjarnef commented
@iOvergaard I added that.

Furthermore I think it would be useful to specify `dateStringFormat` to parse the date. See the issue:
https://github.com/umbraco/Umbraco-CMS/issues/13477

The date string format `YYYY-MM-DD HH:mm:ss` works fine we default date format, but I think there has been issues when developers change the default format (or I in my use-case used `dateHelper.getLocalDate()` to format date value returned from  "Label (datetime)" which seems to return date in format `MM/DD/YYYY HH:mm:ss`.

But the functions in `dateHelper` doesn't allow to specify the date string parsing format: https://momentjs.com/guides/#/parsing/known-formats/

2022-11-29 10:55 UTC, iOvergaard commented
@bjarnef You are right, it would make sense to allow an override of the formatting string in DateHelper. Feel free to create a new PR for that, if you'd like, and simply reference this comment.

I will merge this since it has been approved and fixes the initial issue 👍

2022-11-29 10:56 UTC, merged

2022-12-14 12:45 UTC, nul800sebastiaan commented
Cherry picked for 10.4.0 aaababca9bb325544350f0e248041a094b70d2e1