V11: Allow changing logging directory from configuration
umbraco/Umbraco-CMS pull request #13485
Opened 2022-11-28 07:52 UTC by bergmania

2022-11-28 13:26 UTC, Zeegaan requested changes
Found a few small changes

2022-11-28 13:26 UTC, Zeegaan commented on src/Umbraco.Infrastructure/Logging/Serilog/LoggerConfigExtensions.cs
> +        [Obsolete("Will be removed in the Umbraco 13.")]
```suggestion
        [Obsolete("Will be removed in Umbraco 13.")]
```

2022-11-28 13:26 UTC, Zeegaan commented on src/Umbraco.Infrastructure/Logging/Serilog/LoggerConfigExtensions.cs
> +        [Obsolete("Will be removed in the Umbraco 13.")]
```suggestion
        [Obsolete("Will be removed in Umbraco 13.")]
```

2022-11-28 13:26 UTC, Zeegaan commented on src/Umbraco.Core/Constants-SystemDirectories.cs
> +        [Obsolete("Use LoggingSettings.GetLoggingDirectory() instead")]
We should mention what version we want to remove this (also as a note for ourselves)
```suggestion
        [Obsolete("Use LoggingSettings.GetLoggingDirectory() instead, will be removed in Umbraco 13.")]
```

2022-11-28 13:27 UTC, Zeegaan commented
Setting the `Umbraco/CMS/Logging/Directory` and starting it with `~` results in some weird behavior for me, we now create the `~` folder, with both the Test & umbraco folder, that both contains the logs 😅  
![image](https://user-images.githubusercontent.com/70372949/204289126-529868ff-11c0-4e08-a7f3-6573dc87c1f3.png)

2022-11-28 13:39 UTC, bergmania commented
> Setting the `Umbraco/CMS/Logging/Directory` and starting it with `~` results in some weird behavior for me, we now create the `~` folder, with both the Test & umbraco folder, where one contains the old logs, and the other contains the new ![image](https://user-images.githubusercontent.com/70372949/204289126-529868ff-11c0-4e08-a7f3-6573dc87c1f3.png)

Who would have expected a `return` statement to be important 🙈

2022-11-29 06:27 UTC, Zeegaan commented
Looks good, tests good 🎉

2022-11-29 06:27 UTC, merged