fix: #12253 Anchor picker does not appear
umbraco/Umbraco-CMS pull request #13492
Opened 2022-11-28 16:50 UTC by marcoteodoro

This relates to #12253 

### Steps to test 

1. Install Umbraco v11 
2. Use database attached [Umbraco.sqlite.zip](https://github.com/umbraco/Umbraco-CMS/files/10105668/Umbraco.sqlite.zip)
3. Open umbraco with u/n : marcoteodoro@double.pt p/w: 0123456789
4. Open destination node and create a new anchor link from the origin node. (you will see that anchor links from the blocklist editor and grid editor are listed on the dropdown)

![chrome-capture-2022-10-28](https://user-images.githubusercontent.com/3866444/204335189-2a25d2cf-e7b3-4e55-bfea-5af52c9dc8a8.gif)

### Description

`GetAnchorValuesFromRTEs` method was updated to include `BlockList` and `BlockGrid`
https://github.com/umbraco/Umbraco-CMS/blob/c9410391bf5cc7a05c138208fbbbb404e85847bf/src/Umbraco.Core/Services/ContentServiceExtensions.cs#L80-L80

on top of this, i had to include this line of code `var rteUnescaped = Regex.Unescape(rteContent);` to make the regex work. https://github.com/umbraco/Umbraco-CMS/blob/c9410391bf5cc7a05c138208fbbbb404e85847bf/src/Umbraco.Core/Services/ContentServiceExtensions.cs#L103-L103

However, one thing i noticed is that this that when the culture variable is assigned with `*` this method is always returning null contentProperty.GetValue(culture)?.ToString();`

So this PR is just an initial commit to see what others can suggest. Is this last issue a known issue? or I'm not using it correctly?

2023-05-27 09:45 UTC, lauraneto commented
Olá @marcoteodoro , 🙂

Thank you for your contribution! And really sorry for the long delay. 😣

I reviewed and tested your pull request and I noticed that your solution only works when you have a block list (same for block grid) property in your document that directly contains a block with an RTE inside, it does not work when you have more nesting (a block inside a block).
This is because you are only unescaping the RTE content once and for each layer of nesting the content gets more and more serialized.

While this is already a nice improvement, I wonder, what do you think about instead of unescaping the content, just adjusting the regex instead?
For example, if we change it to something like `<a id=\\*\"(.*?)\\*\">`, it should allow for any nesting level to be matched.

About your question regarding the culture, with your database and my own, I never got it to be `*` when using the link picker UI. (`GetUrlAndAnchors` always assigns a culture or null, if it would be `*`).
If you have reproduction steps do let me know so I can test, but either way, as this is a public method that can be called with `*` I think the fix is good nonetheless.

2023-05-27 10:17 UTC, lauraneto requested changes
Unfortunately I can't suggest an edit on the regex (GitHub doesn't allow me to suggest edits in unchanged code 😅).
But if you do the suggested changes and update the regex as per my other comment it should do the trick. But please verify! 🙂

2023-05-27 10:17 UTC, lauraneto commented on src/Umbraco.Core/Services/ContentServiceExtensions.cs
> +        }
```suggestion
        culture = culture is not "*" ? culture : null;
```
Looking at similar code, it seems like normally it should just default to `null`.

2023-05-27 10:17 UTC, lauraneto commented on src/Umbraco.Core/Services/ContentServiceExtensions.cs
>              result.Add(match.Value.Split(Constants.CharArrays.DoubleQuote)[1]);
```suggestion
            result.Add(match.Groups[1].Value);
```
No need to be manipulating strings when we already have the capture group and this change is required for the new regex.

2023-05-27 10:17 UTC, lauraneto commented on src/Umbraco.Core/Services/ContentServiceExtensions.cs
> +        MatchCollection matches = AnchorRegex.Matches(rteUnescaped);
```suggestion
        MatchCollection matches = AnchorRegex.Matches(rteContent);
```

2023-05-27 10:17 UTC, lauraneto commented on src/Umbraco.Core/Services/ContentServiceExtensions.cs
> +using Umbraco.Cms.Core.HealthChecks;
```suggestion
```

2023-05-27 10:31 UTC, abjerner commented
Maybe not for this PR, but in general it might be worth looking at the anchor picker from another angle. Right now it's very much based on RTEs as emphasized by the method name: `GetAnchorValuesFromRTEs`.

I'd say their could be plenty of other things that could be used as an anchor. Eg. when using the block list, each block item could potentially be an anchor. That's a use case that I've recently had where editors want to deep link to specific block elements. I don't think the anchor picker has been updated to properly support the grid and now the block list, although it probably should have been.

There really isn't a good way to support this with the current implementation. The `GetAnchorValuesFromRTEs` method is also static meaning developers don't really have a way to override the default behavior.

So maybe an `IAnchorProvider` interface could be introduced, and used instead. The default implementation could be that of the existing `GetAnchorValuesFromRTEs` or Marco's proposed changes, but if set up correctly with dependency injection, developers can override the default implementation.

2023-06-16 11:43 UTC, lauraneto commented
Hi @abjerner ,
I totally see your use case (as I also have that same scenario on most of my projects 😅).
But yes, might be best to create a separate discussion/issue regarding this, so we can work on it on top of this pull request (and maybe discuss if there is a solution that we can build within Umbraco or if indeed an interface would be the way to go, so at least we (umbraco devs) can have control over the behavior if we want).

2023-06-16 12:36 UTC, lauraneto approved these changes

2023-06-16 12:40 UTC, merged

2023-06-16 12:52 UTC, lauraneto commented
Hi @marcoteodoro ,

I have just merged this pull request!
Thanks again for the contribution and it was nice to see you in Codegarden (and also see you finish this one during the hackathon 🙂).

I do see that this is your first merged PR, so many congrats!
If you have an account on [our.umbraco.com ](https://our.umbraco.com/) then drop a comment below with your account name and @nul800sebastiaan will add a shiny new contributor badge to your profile. 🏆

Thanks again, and looking forward to your next PR... Or seeing you in the next Codegarden, maybe? 😄

2023-06-16 15:52 UTC, marcoteodoro commented
Hi @lauraneto,

I am thrilled to see my first pull request merged, and I am very grateful for your support throughout the process. The experience at Codegarden was indeed an enriching one, and having the opportunity to complete this PR during the hackathon was a milestone I will always cherish.

Your guidance and positive feedback have inspired me to contribute more, and I look forward to the journey ahead with great excitement. This feels like just the beginning, and I am eager to keep learning, growing, and positively impacting our community. 

Here's my profile link on our.umbraco.com: https://our.umbraco.com/members/marcoteodoro/. I look forward to seeing that shiny new contributor badge on my profile, @nul800sebastiaan! 🏆

I'm already counting down the days until the next Codegarden. It would be wonderful to see you and the team there again, and who knows, maybe even present another pull request or two. 😉

Once again, thank you for everything. Here's to many more collaborative experiences and shared successes in the future. Cheers!

See you all next year!

2023-07-04 08:33 UTC, nul800sebastiaan commented
Whoop whoop @marcoteodoro! Pleasure to have you at the hackathon and as a contributor! 🎉 You have your contrib badge to show off now and some more good news, this fix will also be available in v10 and 11, cherry picked in 2f35967bb28ca118a443580209e74fac42a682a3

2023-07-04 08:49 UTC, marcoteodoro commented
Many thanks, @sebastian-claesson! and once again @lauraneto! I'm I right to think this will be released on the next v10 release? and if so when is that going to happen?