fix for #13623 by hiding Member Edit Action Menu on Infinite editing …
umbraco/Umbraco-CMS pull request #13624
Opened 2022-12-29 20:28 UTC by robertjf

…for consistency

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description
This fixes #13623 by hiding the Action Menu when the Member is edited in the Infinite Editor.  This brings it in line with the experience of editing Media or Content items in the Infinite Editor.

For steps to reproduce, see ticket #13623

2022-12-30 02:21 UTC, mikecp requested changes
Hi @robertjf,

Thanks for spotting this issue and providing the fix  👍

Before merging, may I ask you to add the trailing ";" at the end of the code you added 😁? It might sound picky but it's best to stay inline with the rest of the code I think 😅

Also, could you maybe quickly check the behavior for @Zeegaan 's scenario as described in #13623? On my pc the action menu is still visible in that case, so I'm wondering if it's just me...

Thanks and cheers !!

2022-12-30 02:44 UTC, robertjf commented
@mikecp oh of course! Not sure how I missed that... will get it fixed :)

2022-12-30 07:35 UTC, Zeegaan commented
Tests out great 🎉 I will let @mikecp merge this if he is happy with the code 😁

2022-12-31 02:45 UTC, mikecp approved these changes

2022-12-31 02:51 UTC, mikecp commented
Thanks @robertjf for the quick check/fix, it works great now 🎉
So let's merge this, as @Zeegaan suggests 😁

Cheers and (almost) Happy New Year !! 🎆

2022-12-31 02:51 UTC, merged

2023-03-16 08:19 UTC, nul800sebastiaan commented
Cherry picked for 10.5 in 4b2af296be06093890eee3dad3612d0dc16d261d