Updated the maximum Node version supported
umbraco/Umbraco-CMS pull request #13940
Opened 2023-03-09 15:23 UTC by richarth

Building the current version of the back office is only supported on Node v16 and earlier so have updated the docs to reflect that.

2023-03-09 16:37 UTC, JasonElkin requested changes
Hey @richarth, thanks for updating this, it is an interesting one...

Node v16.19.1 is required to run the tests, but just running the build-only gulp tasks works all the way up to v19.7.0 (current latest version).

When running the frontend build as part of the default (.NET/C#) project build the tests are skipped, so there is still no upper limit when it comes to "building" Umbraco from source.

If you think it would be helpful, perhaps you could add a separate note in here about the node version required for running the tests?

2023-03-09 16:37 UTC, JasonElkin commented on .github/BUILD.md
> +  * [Node.js v14 - v16.19.1](https://nodejs.org/en/download/)
```suggestion
  * [Node.js v14+](https://nodejs.org/en/download/)
```

2023-03-09 16:37 UTC, JasonElkin commented on .github/BUILD.md
> +  * [Node.js v14 - v16.19.1](https://nodejs.org/en/download/)
```suggestion
  * [Node.js v14+](https://nodejs.org/en/download/)
```

2023-03-14 15:13 UTC, JasonElkin commented
Assuming [this PR](https://github.com/umbraco/Umbraco-CMS/pull/13968) gets merged, the gulp tests (and default gulp build) will then work on all Node.js versions from 14 to 19.

2023-03-15 11:56 UTC, nul800sebastiaan commented
Thanks both @richarth for helping with the updates and @JasonElkin for fixing https://github.com/umbraco/Umbraco-CMS/pull/13968 so that the requirements span a nice wide range of node versions again. Much nicer to be able to support the latest LTS of node!

2023-03-15 11:56 UTC, merged

2023-03-15 11:57 UTC, nul800sebastiaan commented
FYI: I've not put any additional labels on, this is an update that only affects contributors, not an actual Umbraco release. 

Thanks again!

2023-03-15 17:21 UTC, richarth commented
Thanks @JasonElkin and @nul800sebastiaan for fixing this.  It's going to make getting started contributing much smoother.