V13: Rework attempt pattern to use userkey
umbraco/Umbraco-CMS pull request #13964
Opened 2023-03-14 08:33 UTC by Zeegaan

# Notes
- Rework all services to take a userKey instead of id
- Don't touch the obsolete ones to avoid breaking changes

2023-03-20 13:56 UTC, elit0451 requested changes
Great work with all those changes 💪 🙌 

I've left a few comments and suggestions 😌 We also need to fix the pipelines before merging

2023-03-20 13:59 UTC, Zeegaan commented on src/Umbraco.Web.BackOffice/Controllers/TemplateController.cs
> -    }
This consructor will be removed in v13 anyways, I just made the change to keep the template controller working for now 😁

2023-03-21 11:38 UTC, elit0451 commented on src/Umbraco.Core/Services/DataTypeService.cs
> +
```suggestion
            
```

2023-03-21 11:41 UTC, elit0451 approved these changes
Looks good 💪 Let's get this merged in!

2023-03-21 11:41 UTC, merged