XPath can unambiguously use $site/$parent
umbraco/Umbraco-CMS pull request #14127
Opened 2023-04-19 18:55 UTC by karlmacklin

This fixes https://github.com/umbraco/Umbraco-CMS/issues/13958

### Description

After this commit here https://github.com/umbraco/Umbraco-CMS/commit/8d2ee3a6d4bfbe650750e6980649ee57706248ef we lost the functionality to evaluate `$site` and `$parent` as XPath variables inside a Multinode Treepicker during the creation of a new node where said picker is a property.
Before the commit, the meaning of `$current` and `$parent` was also ambiguous, changing depending on whether or not you are creating a new node or not.

There is a blog entry explaining how you previously could work around the issue:
https://www.dot-see.com/blog/getting-the-right-starting-node-for-multinode-treepicker-with-xpath/
However with today's code one can't use the Multinode Treepicker with XPath correctly during node creation at all, if they depend on these variables.

This has lead to issue 13958 being raised.

The changes proposed in the code makes sure that the parent node id is always available so the node from `$parent` is always the same regardless of creating a new node or not.

The code does not change how `$current` resolves, as it there is an argument for keeping it as is for the state of creating a new node. The use cases that has raised issue 13958 does also not depend on `$current`. Most likely you would set up a treepicker for this scenario to pick from nodes that are children to your `$current`, at which point you already have it published.

My knowledge in XPath is limited to what has been discussed in the linked blog article and the linked issue, and our own company's use case. There is very little documentation I have found helpful to understand the syntax in the context of Umraco.

So while I am confident the proposed code will suffice and not introduce any regression, it would be prudent to have someone somewhat experienced in XPath within Umbraco have a look at this.

2023-05-11 09:23 UTC, nikolajlauridsen requested changes
Hey @karlmacklin thanks for the PR and great work 💪 🎉 

Just had a look and a test at this, and it fixes the issue you mentioned and doesn't regress the #13657 PR so on that front we're all good to go as far as I'm aware.

I did notice a small thing though with the frontend code, I think we should try to make this non breaking by simply having both the methods (this will be removed in the new back office anyway) 

Once that's done we're good to merge 🚀🎉

2023-05-11 09:23 UTC, nikolajlauridsen commented on src/Umbraco.Core/Xml/UmbracoXPathPathSyntaxParser.cs
> +    [Obsolete("This will be removed in Umbraco 13. Use constructor with parentId instead")]
```suggestion
    [Obsolete("This will be removed in Umbraco 13. Use ParseXpath which accepts a parentId instead")]
```

2023-05-11 09:23 UTC, nikolajlauridsen commented on src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
>          },
I don't think it's great to rename this method, it seems like an unnecessary breaking change (I'm guessing we'd like to cherry-pick this fix to 10/11 too), so I'd suggest adding the `getByXPath` as a new method, and keeping the `getByQuery` so we don't break peoples existing code. 😄

2023-05-14 15:34 UTC, karlmacklin commented
Good call @nikolajlauridsen 

I've made some changes and while making sure legacy usage is working properly I realized we still always need to "process" $site and $parent variables as well, otherwise they are not transformed at all which results in a Xml namespace-related crash deeper within the published content xpath fetching.

Also, while testing any case I could think of, I noticed there is a bug in the current `contrib` code (please feel free to test this yourself) where using $parent for example (with getByQuery entity function I am bringing back as deprecated) can net you this error:
`TypeError: Cannot read properties of null (reading 'udi')`

And this stems from assuming you are returned an entity that has a udi at:
https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js#L251

But given how the current code has problems with xpath parsing we are getting a null returned instead of an actual entity.
This is the case when creating a new node that has the MNTP, not on existing nodes.

2023-05-15 06:42 UTC, nikolajlauridsen approved these changes
Looks great to me now 👍 Let's get this merged 🎉

2023-05-15 06:42 UTC, merged

2023-05-15 06:49 UTC, nikolajlauridsen commented
Cherry picked to V10 in b3bedb4efee8866a7c5cfee9be2414adcf8f0a8a

2023-06-19 08:37 UTC, Zeegaan commented
@karlmacklin Sorry for the confusion here, it will be in 11.4.1 👍