Added test for checking if settings model contains default value
umbraco/Umbraco-CMS pull request #14513
Opened 2023-07-06 13:24 UTC by andr317c

Added tests for checking if the block list editor settings model contains the defined default value.

Also did some cleaning up on blockListEditorContent file

2023-07-07 08:30 UTC, Zeegaan requested changes
Few small things 😁

2023-07-10 07:56 UTC, andr317c commented on tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockListEditor/blockListEditorContent.spec.ts
> +  }
Fixed 💪

2023-07-10 07:56 UTC, andr317c commented on tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockListEditor/blockListEditorContent.spec.ts
> +    await expect(page.locator('.umb-block-list__block--view').nth(0)).toHaveText(contentElementName);
That's a good point, no reason to have count when we only have 1 😆

2023-07-10 08:12 UTC, jdpnielsen approved these changes

2023-07-10 08:38 UTC, Zeegaan approved these changes
LGTM 👍

2023-07-10 08:38 UTC, merged