Add missing list view usages to data type references (#14485)
umbraco/Umbraco-CMS pull request #14617
Opened 2023-07-31 11:42 UTC by ustadstar

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14485

Please see the issue for the description of the bug including the steps to reproduce. 

My changes do show the content types which use a list view as a container under references on the info tab of a datatype. However my changes are not the ideal solution to the problem. A better solution for the future would be a change in the database schema to add a relation between the list view (the isContainer field on contentType is now a boolean, without any relation). 

My solution finds the relation between the datatype and list views as a container as follows:

- We check if the current data type is a list view, if it is we continue 
- Next we check if the name of the datatype matches the custom list view name.  The logic behind this is the same as in: ListViewContentAppFactory.cs. If it is not a custom list view we continue
- Next we check if the datatype name matches the default content type list view name. if not we return an empty array.

To test this PR please follow the steps below.

**Test with a default list view**
1. Navigate to settings
2. Choose a document type
3. Open the list view tab
4. Enable list view and save
5. Navigate to settings -> data types -> List View - Content
6.  Open the info panel
7.  Check if List View - Content is listed under references

![image](https://github.com/umbraco/Umbraco-CMS/assets/36473707/a5dabe9c-e15d-4ccf-a41e-7cc72abcd8f5)

**Test with a custom list view**
1. Navigate to settings
2. Create a new document type, e.g. "Content Page"
3. Open the list view tab
4. Enable list view and choose "Create a custom list view"
5. Save the new document type
6. Navigate to settings -> data types -> List View - contentPage
7.  Open the info panel
8.  Check if Content Page is listed under references

![image](https://github.com/umbraco/Umbraco-CMS/assets/36473707/e31568cf-c3bc-4a40-8244-7901e785fc40)

2023-07-31 17:54 UTC, nul800sebastiaan requested changes
Thanks @ustadstar - we'll have a better look soon, but to begin with I've left you a comment to update the interface so it's not a breaking change.

2023-07-31 17:54 UTC, nul800sebastiaan commented on src/Umbraco.Core/Persistence/Repositories/IDataTypeRepository.cs
> +    IReadOnlyDictionary<Udi, IEnumerable<string>> FindListViewUsages(int id);
This is a breaking change, anybody already implementing this interface will get a build error and plugins that haven't been updated will make the whole site error out.

Luckily there's an easy way to work around this and that is to introduce a default implementation, an example can be seen here: https://github.com/umbraco/Umbraco-CMS/pull/11867#issuecomment-1178869417

2023-07-31 17:55 UTC, nul800sebastiaan commented on src/Umbraco.Core/Services/IDataTypeService.cs
> +    IReadOnlyDictionary<Udi, IEnumerable<string>> GetListViewReferences(int id);
Same as the other interface, this is also a breaking change, which can be fixed in the same way.

2023-08-06 13:38 UTC, ustadstar commented
@nul800sebastiaan I have added a default implementation for both methods in the interfaces.

2023-09-24 13:40 UTC, ustadstar commented
Hi @nul800sebastiaan, did you have time to review the changes?

2024-02-06 14:50 UTC, merged

2024-02-06 14:51 UTC, georgebid commented
Hey, @ustadstar! I thought I'd jump in here and review this PR 😄 Thanks a lot for making those change requests, I have tested this PR and everything looks good to me, therefore I have merged this one in! Thanks for fixing #14485 🚀 You'll see this in the next release.

2024-02-06 15:43 UTC, emmagarland commented
Great stuff all!