Bug fix 14351
umbraco/Umbraco-CMS pull request #14620
Opened 2023-07-31 21:40 UTC by rammi987

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes [#14351](https://github.com/umbraco/Umbraco-CMS/issues/14351)

### Description
Fixing the bug where if using the the `.Value()` method with either a culture parameter or the fallback the whole site change state of the initial language set from the PublishedRouter.

This delete code was introduce by the PR [#13889](https://github.com/umbraco/Umbraco-CMS/pull/13889) but it made the VariationContext change now only for the current operation but the rest of the request. This means that if having a Danish site with fallback to english. So if you said `model.Value("someAlias", fallback: "en");` or using `model.Value("someAlias", "en");` the site end result for the users is a mismatch or both Danish and English content.

The best current solution is to reset it and avoid this bug is to do something like this:
```
var realContent = model.Value("someAlias", "en");
_ = model.Value("someAlias", "da");
```

Looking back to the original bug [#13889](https://github.com/umbraco/Umbraco-CMS/pull/13889)
The problem was inside a Blazor app where there was a language selector, so you could change the App from English to Swedish and back. The initial state was English. So clicked on the Swedish you hit this method.
```
private void SetEnglish()
{
  Content = "English";
  var en = new CultureInfo("en");
  CultureInfo.CurrentCulture = en;
  CultureInfo.CurrentUICulture = en;
  
  using (var scope = ScopeProvider.CreateScope(autoComplete: true))
  {
    using (var context = UmbracoContextFactory.EnsureUmbracoContext())
    {
    var settings = (Settings)context.UmbracoContext.Content.GetAtRoot().ElementAtOrDefault(1);
    Content = settings.Body.ToHtmlString();
    }
  }
}
```

But here we only changing the CultureInfo witch don´t change the way how the ModelsBuild choose the content. So the idea behind the bug and PR was with great intentions.

Problem is, that when navigating to a Blazor app, it either goes thouge the `PublishedRouter` and get set the correct VariationContext, or VariationContext is set to the default language set inside Umbraco. But all interaction is now in the app. So changing the language with the method above where we skip the routing pipeline, do not change the VariationContext for the request. The best way is to compare a Blazor App with Api Endpoint where the VariationContext is skipped as well.

So in the end if the method above was like this where we change the VariationContextAccessor.
```
private void SetEnglish()
{
  Content = "English";
  var en = new CultureInfo("en");
  CultureInfo.CurrentCulture = en;
  CultureInfo.CurrentUICulture = en;
  _variationContextAccessor.VariationContext = new VariationContext("en");
  
  using (var scope = ScopeProvider.CreateScope(autoComplete: true))
  {
    using (var context = UmbracoContextFactory.EnsureUmbracoContext())
    {
    var settings = (Settings)context.UmbracoContext.Content.GetAtRoot().ElementAtOrDefault(1);
    Content = settings.Body.ToHtmlString();
    }
  }
}
```
The bug was solved, and is streamline with what we normal do inside a Api-endpoint again where the variationContext setter is skipped so we need to manual set it, change or what we need to do, it is not enouge to change the systems CultureInfo.

This bug arffected both Umbraco 10.5.0 and up, Umbraco 11.3 and up and Umbraco 12 and up. 
This bug simple make all this infomation inside the Docs unstabil https://docs.umbraco.com/umbraco-cms/reference/querying/ipublishedcontent/properties#fallbacks do the fatch the whole request language is change and again ends up with site with is a mismatch between mutiple languages, and for some customer witch upgrades as https://github.com/umbraco/Umbraco-CMS/issues/14351#issuecomment-1635652284 just without payed any attention it could lead to end-user getting sites again in multiple language mismatch.

2023-08-07 07:44 UTC, nul800sebastiaan requested changes
Thanks @rammi987 - I can see that #14620 has been problematic, which was not the intention. 

The deletion on the interface and method on `PublishedValueFallback` would be breaking changes so we need to obsolete them properly. I'm happy with reverting `EventuallyUpdateVariationContext` and for @joelmandell who had the initial problem, the way to fix that is noted on the issue by @kjac https://github.com/umbraco/Umbraco-CMS/issues/14071#issuecomment-1510697854

2023-08-07 07:44 UTC, nul800sebastiaan commented on src/Umbraco.Core/Models/PublishedContent/IPublishedValueFallback.cs
> -    IVariationContextAccessor VariationContextAccessor { get { throw new NotImplementedException(); } set { throw new NotImplementedException(); } }
This is a breaking change, method should be Obsoleted and removed in v14.

2023-08-07 07:44 UTC, nul800sebastiaan commented on src/Umbraco.Core/Models/PublishedContent/PublishedValueFallback.cs
> -    public IVariationContextAccessor VariationContextAccessor { get { return _variationContextAccessor; } }
This is a breaking change, method should be Obsoleted and removed in v14.

2023-08-07 07:56 UTC, joelmandell commented
My apologies

2023-08-07 08:04 UTC, sniffdk commented
@joelmandell No worries mate, we know it was made with the best intentions, as was the approval of the PR in the first place, everything is good 😃❤️

2023-08-07 08:20 UTC, rammi987 commented
@joelmandell No need to say sorry <3

2023-09-07 08:34 UTC, sniffdk commented
Hey @nul800sebastiaan , any news on this PR? Would be great to have it done and put in a release schedule soon 😅

2023-10-16 11:58 UTC, rammi987 commented
@nul800sebastiaan I promised to ping you 😊

2023-10-17 11:24 UTC, merged

2023-10-17 11:24 UTC, nul800sebastiaan commented
Real sorry for the delay people! I have finally been able to get to it, this is a great fix and will indeed just revert the previous PR. If anyone was relying on the behavior introduced by #13889 then they will need to update their code in a different way by specifying the culture themselves, as noted in @kjac's comment here: https://github.com/umbraco/Umbraco-CMS/issues/14071#issuecomment-1508085299 (cc: @joelmandell you might need to update your code before 12.3 comes out).

Thanks again for all the feedback! And great job at sending us this PR @rammi987 🙌 #h5yr!

2023-10-26 09:49 UTC, nul800sebastiaan commented
Cherry-picked for v10 in bde88caf14e30fb5ff8547c629aa6133a7d07338