fix for #14698
umbraco/Umbraco-CMS pull request #15159
Opened 2023-11-07 12:13 UTC by huzzi

The Xpath Query for the Multinode Treepicker does not work when used on a new node in the content tree. Once the node is saved the Xpath Query will work as expected.

Do not know what version of Umbraco this started to happen with however I can confirm that it was functioning properly with Umbraco 10.3.2 and doesn't work with 11.2.2 and above.

Specifics
Treepicker documentation and how to work with XPath can be found here:

https://github.com/umbraco/Umbraco-CMS/issues/14698

### Description

Steps to reproduce
You can reproduce by creating a simple Document Type / Content Structure in Umbraco.

Home (Document Type - alias 'home')
Page type 1 (Document Type - Page type 1 allowed below Home - alias 'pageType1')
Page type 2 (Document Type - Page Type 2 allowed below Home and below Page type 1 - alias 'pageType2')

Create a Multinode Treepicker with the following xpath query:

$current/ancestor-or-self::home/pageType1

This XPath picker should find Home and then first node using pageType1 document type. It should then list all nodes below.

Add this picker to page type 2

In the content Tree add:

Home
---Text page 1 (Page Type 1)
------Sub page 1
------Sub page 2
---Text page 2 (Page Type 2) DO NOT PUBLISH

The picker on page type 2 should only show Sub page 1 and Sub page 2 however it will show all nodes in the content tree.

If you save and publish the page and then try the picker again, it will work as expected and only show Sub page 1 and Sub page 2.

The location of the unpublished node is therefore no longer working as it did in previous versions of Umbraco.

2023-11-08 10:48 UTC, huzzi commented
> Thank you @huzzi Someone from the Core team will look into this PR soon!

This issue is also on V9 and V13. Please it appropriately. Thank you.

2023-11-23 12:45 UTC, huzzi commented
Can someone please review this pr?

2023-11-29 13:12 UTC, nul800sebastiaan commented
Thanks you for your patience @huzzi - we'll need a little more time, but we'll get back to you!

2024-02-02 12:13 UTC, Ruddy2007 commented
Any movement on this? 

We have just noticed the issue in Umbraco 13 and need to resolve it.

2024-02-07 14:47 UTC, lauraneto requested changes
Hi @huzzi,

Again, thank you for your (first 🎉) pull request and sorry for the delay. 🙏

While your change works for the specific case you mentioned, I'm worried it won't work when you have different queries that are not `ancestor-or-self::`, as that makes it so the level doesn't matter.
Although, I just noticed in the query help that it says `$current: Current page or closest found ancestor`, so maybe that was already the case before? I might double check this with HQ and come back to you! 🙂

Either way, I left a comment regarding the `if` change. Let me know what you think!

2024-02-07 14:47 UTC, lauraneto commented on src/Umbraco.Core/Xml/UmbracoXPathPathSyntaxParser.cs
> -        if (nodeContextId.HasValue)
Won't this change make it so that if there is a `parentId` that will always be used instead of the `nodeContextId` for setting the `$current`?

2024-02-08 13:41 UTC, lauraneto commented
Ok, I did some additional investigation on this.

In version `10.3.2` there was no logic to check for the `parentId` because the `nodeContextId` received by the function was in fact the parent id and not `0` as it is now (only when creating the node, of course).
Then I came across https://github.com/umbraco/Umbraco-CMS/pull/14127 which feels like it was also a fix due to the change above, but did in fact mention they did not handle `$current` as it was not part of the issue reported and it was also not clear how it should behave.

As far as I can see, the previous behavior, where `$current` had an effect was indeed using the `parentId` as `$current` so this change would make it work as it did before.
I will still do a double check with HQ just in case they have more thoughts on this 😊

2024-02-08 16:11 UTC, lauraneto commented
Hi again @huzzi ,
I double checked with HQ and if it was working like that before, then it is ok to keep having the same behavior (using the parent as current on new nodes) 🙂
So, when you have the time, could you check my comment?
Thanks 🙌

2024-03-06 17:41 UTC, lauraneto approved these changes

2024-03-06 17:45 UTC, merged

2024-03-06 17:55 UTC, lauraneto commented
Hi @huzzi,

As I haven't heard from you since I left feedback, I have now adjusted and merged the changes.
Thank you so much for your help fixing this one! 🙌

Do you have an Our Umbraco account? If so, please drop here your username so we can give you a contributor badge. 🚀

2024-04-17 11:16 UTC, huzzi commented
> Hi @huzzi,
> 
> As I haven't heard from you since I left feedback, I have now adjusted and merged the changes. Thank you so much for your help fixing this one! 🙌
> 
> Do you have an Our Umbraco account? If so, please drop here your username so we can give you a contributor badge. 🚀

@lauraneto I'm so sorry I didn't see these messages till now and thank you sorting making the changes.