Fix alt attribute of logo image on login page
umbraco/Umbraco-CMS pull request #15182
Opened 2023-11-11 09:38 UTC by mehrdadab

### Prerequisites

- [x] I have added steps to test this contribution in the description below
To test it: 
- Visit the login page: /umbraco#/login/false, then the lighthouse accessibility tool should not show "missing alt attribute"
- Visit the Login page, right-click on the page and press Inspect on the menu then search for _assets/img/application/umbraco_logo_white.svg_ to find the logo img tag. It should contain **alt="Umbraco"**

If there's an existing issue for this PR then this fixes 
Related issue: https://github.com/umbraco/Umbraco-CMS/issues/15069
### Description
I just added alt="Umbraco" to the logo on the login page

2023-11-11 11:42 UTC, mikecp requested changes
Hi @mehrdadab ,

Thank you for this update!

This logo image can in fact be set to whatever the developer/client wants in the appSettings (via Content:LoginLogoImage), so it might actuially not be the Umbraco Logo that is displayed there but the company logo for example.

So I think it might be interesting to change the text to "Logo" or something like that so that it fits all situations 😅
What do you think?

Cheers!

2023-11-14 11:52 UTC, mehrdadab commented
Hi @mikecp ,
Before setting the value, I checked another version of Umbraco and noticed it had alt="Umbraco" so I did the same to keep it consistent, but I agree that if users can change the logo image then Umbraco as alt is incorrect.
I can change it to a "Logo" or "company logo" or as a more complicated solution, we can read the alt value from the settings file.

2023-11-15 22:57 UTC, mikecp commented
Hi @mehrdadab , thanks for your feedback!

If I remember correctly, in previous versions it was indeed not possible to change the logo, and therefore it was always the Umbraco logo. So that's probably why there was "Umbraco" as alt, and also probably why it was replaced by an empty string in more recent versions...

I would updated this to "Logo", as this is the most global way of defining what it is 😅
"Company logo" might be wrong if they actually keep the Umbraco Logo, and I know that HQ wants to avoid complexifying the settings files 😉

Thanks!

2023-11-16 11:43 UTC, mehrdadab commented
Hi @mikecp 
I agree, Logo is the best choice here.  
Thanks for updating.
Cheers,

2023-11-29 13:06 UTC, nul800sebastiaan commented
Hey all, I don't think this actually adds anything, if it say "Logo" then you have learned nothing, if it says: "Logo for cardealership Ultracool" then maybe it is helpful. But in general, it is not a content page, it's a functional page and what helps people with screenreaders is to get to the login from as soon as possible. This is also why there is currently an empty alt attribute:

> Decorative images do not need to be announced by the screen reader, so if the alt attribute is empty ( alt="" , aka a "null" tag) it will not be announced to the user.
Source: https://accessibleweb.com/question-answer/when-should-i-use-a-null-or-empty-alt-tag/#:~:text=Answer,be%20announced%20to%20the%20user.

So thanks for the help @mehrdadab but I'm going to close this one as the current functionality is just fine. Thanks again!

2023-11-29 13:06 UTC, closed without merging