Add HealthCheckCompletedWebhookEvent
umbraco/Umbraco-CMS pull request #15337
Opened 2023-12-01 08:26 UTC by erikjanwestendorp

### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
In addition to the "Webhook all the things" [PR](https://github.com/umbraco/Umbraco-CMS/pull/15161) and as suggested by @nul800sebastiaan [in](https://github.com/umbraco/Umbraco-CMS/pull/15276#issuecomment-1833936881) add a `HealthCheckCompletedWebhookEvent`. 

Add to the collectionbuilder: 

```csharp
builder.WebhookEvents().AddHealthCheckWebhooks();
```

or:
```csharp
builder.WebhookEvents().AddAllAvailableWebhooks();
```

2023-12-01 13:11 UTC, emmagarland commented
Hi @erikjanwestendorp ,

Thanks for your PR to add a HealthCheckCompletedWebhookEvent as part of the overall ["Webhook all the things"](https://github.com/umbraco/Umbraco-CMS/pull/15276#issuecomment-1833936881) strategy!

We'll have a gander soon. 

Tagging @nul800sebastiaan since this is targeting a branch we can't merge.

Best wishes

Emma

2023-12-04 13:04 UTC, nul800sebastiaan commented
You were too soon with your update @erikjanwestendorp - Ronald had moved things again in #15345 haha! I fixed the resulting conflict though and this one is now good to go! Thanks for staying on top of it!

2023-12-04 13:04 UTC, ronaldbarendse requested changes

2023-12-04 13:04 UTC, ronaldbarendse commented on src/Umbraco.Core/Webhooks/Events/HealthCheck/HealthCheckCompletedWebhookEvent.cs
> +namespace Umbraco.Cms.Core.Webhooks.Events.HealthCheck;
```suggestion
namespace Umbraco.Cms.Core.Webhooks.Events;
```

2023-12-04 13:04 UTC, ronaldbarendse commented on src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsExtensions.cs
> +            .Append<HealthCheckCompletedWebhookEvent>();
This should use the `WebhookEventCollectionBuilderCms` builder!

2023-12-04 13:04 UTC, ronaldbarendse commented on src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderExtensions.cs
> +                    .AddHealthCheck();
And lets order this alphabetically!

2023-12-04 13:04 UTC, merged

2023-12-04 13:13 UTC, nul800sebastiaan commented
Even worse, I broke the build! But thanks @ronaldbarendse for the quick fix! 8a65c002793eefc942f5e289b247fd2d3df0d01a