V14 QA Added integration tests to handle authorization of DataType
umbraco/Umbraco-CMS pull request #15366
Opened 2023-12-05 15:16 UTC by nhudinh0309

### Description
Added integration tests about authorization handlers for DataType
Removed unused class and methods corresponding to old Base Class solution

2023-12-06 10:58 UTC, JasonElkin commented
Core collabs can ignore this.

2023-12-06 10:58 UTC, JasonElkin commented
Core collabs can ignore this.

2023-12-08 12:35 UTC, andr317c commented
Needs refactoring to match the new best practice :D

2023-12-11 11:35 UTC, andr317c requested changes

2023-12-11 11:35 UTC, andr317c commented on tests/Umbraco.Tests.Integration/ManagementApi/DataType/DeleteDataTypeControllerTests.cs
>      }
```suggestion
    protected override async Task<HttpResponseMessage> ClientRequest() => await Client.DeleteAsync(Url);
```

2023-12-12 13:38 UTC, andr317c approved these changes

2023-12-12 13:49 UTC, merged