V14 QA Added acceptance tests for Dictionary
umbraco/Umbraco-CMS pull request #15479
Opened 2023-12-19 08:52 UTC by nhudinh0309

Updated api tests for Dictionary
Added .udt files to test the import dictionary function
Added ui tests for Dictionary
Bumped version of helpers

2024-01-22 12:14 UTC, andr317c requested changes
Had a few comments

2024-01-23 04:03 UTC, nhudinh0309 commented
Fixed comments

2024-01-23 07:48 UTC, andr317c requested changes
One comment

2024-01-23 07:48 UTC, andr317c commented on tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Dictionary/Dictionary.spec.ts
```suggestion
import * as crypto from 'crypto';
```
When I ran the API tests for dictionary I got the error ReferenceError: crypto is not defined. So we need to define the import for the test to work

2024-01-23 08:47 UTC, merged