v14: Add Preview controller
umbraco/Umbraco-CMS pull request #15481
Opened 2023-12-19 11:27 UTC by Zeegaan

# Notes
- Add Preview controller

# How to test
- Use swagger to enter preview.
- Assert the cookie has been set.
- Use swagger to call the end preview endpoint
- Assert the cookie has been deleted.

2023-12-19 12:43 UTC, bergmania commented on src/Umbraco.Cms.Api.Management/Controllers/Preview/EndPreviewController.cs
> +        _cookieManager.ExpireCookie(Constants.Web.AcceptPreviewCookieName);
Where is this set?

2024-01-09 13:15 UTC, elit0451 requested changes
A few comments, otherwise it tests out good 💪

2024-01-09 13:15 UTC, elit0451 commented on src/Umbraco.Cms.Api.Management/Controllers/Preview/EnterPreviewController.cs
> +
```suggestion
[ApiVersion("1.0")]
```

This is important as otherwise we see those endpoints as v2 as well

2024-01-09 13:15 UTC, elit0451 commented on src/Umbraco.Cms.Api.Management/Controllers/Preview/EndPreviewController.cs
> +
```suggestion

[ApiVersion("1.0")]
```

This is important as otherwise we see those endpoints as v2 as well

2024-01-09 14:51 UTC, elit0451 approved these changes

2024-01-09 14:51 UTC, merged