Property level validation for Management API
umbraco/Umbraco-CMS pull request #15644
Opened 2024-01-27 07:30 UTC by kjac

### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

TBD

### Testing this PR

Unstructured notes for test scenarios 😄 

- [ ] JSON path in problem details `errors` for complex editor validation errors
- [ ] Create & update always succeeds despite property editor level validation errors
- [ ] Can validate both create and update models (separate endpoints)
- [ ] Publish performs re-validation and fails with appropriate property level validation errors
- [ ] Validation works for both documents and media
- [ ] Problem details response contains status code for all failure states when working with documents and media - not limited to property level validation

2024-01-30 12:24 UTC, Zeegaan requested changes
Found a few small nitpicky things 😊

2024-01-30 12:24 UTC, Zeegaan commented on src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidatorBase.cs
> +            for (var i=0; i<group.Items.Count; i++)
```suggestion
            for (var i = 0; i < group.Items.Count; i++)
```

2024-01-31 07:21 UTC, kjac commented on src/Umbraco.Cms.Api.Management/Controllers/Media/CreateMediaController.cs
>  }
You're absolutely right. That's an oversight. Good catch 👍

2024-01-31 07:23 UTC, kjac commented on src/Umbraco.Cms.Api.Management/Controllers/Document/UpdateDocumentControllerBase.cs
> +        if (content == null)
Fixed in latest

2024-01-31 07:23 UTC, kjac commented on src/Umbraco.Cms.Api.Management/Controllers/Media/CreateMediaController.cs
>  }
Fixed in latest

2024-01-31 07:24 UTC, kjac commented on src/Umbraco.Cms.Api.Management/Controllers/Media/UpdateMediaControllerBase.cs
> +        if (media == null)
Fixed in latest

2024-01-31 07:24 UTC, kjac commented on src/Umbraco.Core/PropertyEditors/Validation/JsonPathValidator.cs
> +                JsonPath = $"{current.JsonPath}.{jsonPathValidationResult.JsonPath}"
Fixed in latest

2024-01-31 07:24 UTC, kjac commented on src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidatorBase.cs
> +            for (var i=0; i<group.Items.Count; i++)
Fixed in latest

2024-01-31 08:21 UTC, kjac commented on src/Umbraco.Core/Models/ContentEditing/ContentCreateResult.cs
> +}
As agreed - no primary constructors (yet)

2024-01-31 09:40 UTC, Zeegaan approved these changes
LGTM 🚀

2024-01-31 09:40 UTC, merged