V14: Invalidate user tokens
umbraco/Umbraco-CMS pull request #15651
Opened 2024-01-31 09:58 UTC by elit0451

## Details
- Invalidating all user tokens when a user is disabled (unapproved) / deleted;
- Invalidating all user tokens when the user access changes - user groups, content / media start nodes;
  - You can check below that these are the only relevant things we keep track in the claims (`startcontentnode`, `startmedianode`, `role`) - when it comes to permissions (general and granular), they are not tied to the user tokens, meaning that they will be resolved at runtime, so we don't need to revoke tokens then.
- Invalidating all user tokens part of a deleted user group; 

> [!NOTE]  
> - Admin tokens are not revoked at the moment;
> - We need to save the state before saving a user (to compare if the access has changed) and before deleting a user group (to get the users part of that group to revoke their tokens) - we are doing that by using the corresponding Saving or Deleting notification and passing such state that will be read on the Saved or Deleted notification.
> - FYI, these are the claims we send for the `Editors` user group for example:
<img width="643" alt="Editors_UserGroup_Claims" src="https://github.com/umbraco/Umbraco-CMS/assets/21998037/12630b57-6df1-4b47-9a99-9bacf695b731">
</br>

## Test
- ⚠️  You need to work with the **Umbraco.Web.UI.New** project;
  - Working with several users is a good idea, so I suggest creating 1 having current groups, 1 having a single newly created group, 1 having the newly created group and one other existing group;
  - It is also a good idea to have some content and media nodes to play around with the content and media start nodes of a user;
  - Consider a testing setup where you can be logged in with several users to verify if their tokens have been revoked - I used several Swagger instances and Authorized in incognito browsers and I made sure I am logged in with the correct user using `GET /umbraco/management/api/v1/user/current` endpoint - there is some magic with the `NewBackoffice` cookie needing to be deleted every time you try to authorize with a new user; Reach out for help if needed! 🙂 
- Verify that the user token is revoked when a user is disabled - you can use `POST /umbraco/management/api/v1/user/disable` endpoint;
- Verify that the user token is NOT revoked when modifying the admin user - you can user `PUT /umbraco/management/api/v1/user/{id}` endpoint;
- Verify that a user token is NOT revoked when modifying other user information than user groups, content/media start nodes;
- Verify that when you delete a user group, all users part of it will have their tokens revoked - you can use `DELETE
/umbraco/management/api/v1/user-group/{id}`.

2024-02-05 12:42 UTC, Migaroez commented
Testing, includes whether action only influence the targeted user(s):
- [x] No revocation when updating user fields that are not considered auth
- [x] Updating user startnode
- [x] Updating usergroup on user
- [ ] Updating startnode of a group the user is part off (Not part of this PR, but should be considered)
- [x] Deleting a group the user is part off
- [x] Disabling a user

2024-02-05 12:44 UTC, Migaroez requested changes

2024-02-06 08:16 UTC, elit0451 commented on src/Umbraco.Cms.Api.Management/Handlers/RevokeUserAuthenticationTokensNotificationHandler.cs
> +            if (user.IsAdmin())
I rearranged the conditions, so basically, if an admin user is still approved and is allowed to log in, we don't want to revoke the admin token when they make accidental changes

2024-02-06 10:22 UTC, Migaroez approved these changes

2024-02-06 12:02 UTC, merged