V14: Member group controller
umbraco/Umbraco-CMS pull request #15669
Opened 2024-02-01 13:18 UTC by Zeegaan

# Notes
- Port of `MemberGroupController` to v14
- Implements `async` versions of all the methods in `IMemberGroupService`
- The `DuplicateName` endpoint has now been moved to the service for validation.

# How to test
- Using swagger, you should
- Create a member group
- Fetch the created member group
- Update the member group name
- Create another member group
- Fetch all member groups, assert both are there
- Try updating one of the member groups to have the same name as the other, this should fail.
- Try creating a member group with an already existing name (the name of either member group) this should fail.
- Try creating a member group with an already existing key (the key of either member group) this should fail.

2024-02-06 12:21 UTC, Migaroez commented
❗ Updating a group with the same name (not the same as another) gives duplicate name

2024-02-06 12:24 UTC, Migaroez requested changes
❗ Updating a group with the same name (not the same as another) gives duplicate name (should just pass)
❗ Deleting a group that does not exist throws a 500 instead of 404

2024-02-08 11:56 UTC, Migaroez approved these changes
Don't forget to update the openapi spec before merging.

2024-02-08 11:57 UTC, Migaroez commented on src/Umbraco.Cms.Api.Management/Controllers/MemberGroup/UpdateMemberGroupController.cs
> +    public async Task<IActionResult> Update(Guid id, UpdateMemberGroupRequestModel model)
Missing 404 response type

2024-02-08 12:08 UTC, Zeegaan commented on src/Umbraco.Cms.Api.Management/Controllers/MemberGroup/UpdateMemberGroupController.cs
> +    public async Task<IActionResult> Update(Guid id, UpdateMemberGroupRequestModel model)
Good catch 👍

2024-02-29 08:16 UTC, merged