Refactor GetChildren method on Content Controller and introduce GetChildrenForSort
umbraco/Umbraco-CMS pull request #15677
Opened 2024-02-03 15:12 UTC by AdamPrendergast

Introduced the GetChildrenFilter class for parameter encapsulation to enable a DRY approach.

This change facilitates the introduction of a new 'GetChildrenForSort' method, allowing precise control over the 'ActionLetter' in the 'FilterAllowedOutgoingContent'.

### Prerequisites

- [ ] I have added steps to test this contribution in the description below

### Description

For reference: please see videos of the original bug here: https://github.com/umbraco/Umbraco-CMS/issues/15608

On a fresh install setup a new editor user and create a simple multi root node structure:

![image](https://github.com/umbraco/Umbraco-CMS/assets/550193/e664dd5d-f303-4f68-af98-a99a7f09b6e7)

For the created user setup a new group:
- Content start node to be on of the root nodes
- Restrict the permission so **only** Sort is enabled in the Structure settings.

![image](https://github.com/umbraco/Umbraco-CMS/assets/550193/afeb020e-e306-463e-bda7-fbb31ffc4f38)

![image](https://github.com/umbraco/Umbraco-CMS/assets/550193/5b962647-d3d2-4d8f-b761-6626ef28d23e)

Set 'Granular permissions' for the start node as:

![image](https://github.com/umbraco/Umbraco-CMS/assets/550193/aa80705f-b853-4343-b677-b7992d81d1c4)

![image](https://github.com/umbraco/Umbraco-CMS/assets/550193/1cbe135b-c959-435e-b5b9-dd286d09ec77)

Assign this group to the created editor user.

Sign in as the editor user.

The Content should be restricted as expected.

The user should now be able to sort the nodes

2024-02-07 00:25 UTC, mikecp commented
Hi @AdamPrendergast,

Thanks for your PR and for the detailed explanations on how to test this 👍
Someone from the core collaborators team will have a look at it soon.

2024-02-07 10:06 UTC, AdamPrendergast commented
Great, thanks @mikecp

Happy to implement any feedback or take a different approach if desired.

2024-02-13 12:59 UTC, nul800sebastiaan requested changes
Thanks Adam, left you a comment after a quick skim!

2024-02-13 12:59 UTC, nul800sebastiaan commented on src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
> -        string cultureName = "") // TODO: it's not a NAME it's the ISO CODE
Hey there @AdamPrendergast - nice refactor! However, this is a public method on a public class so this is a breaking change, we can't have that. Can you do it without changing this method signature?

Note: I have not looked at the rest of this PR at all, so I am not sure if it's good or wanted, but I just wanted to flag this problem while skimming.

From what I can see quickly, I think your intentions are good, but this code is consumed by many people, I would suggest sticking with the pattern (as bad as it looks) and adding a new method with a lot of params instead. As I can see you're also adding a new public class, which can then also be adopted by people so we need to be 100% sure we would want to maintain it. (spoiler: I don't think we'll want to or need to).

2024-02-20 09:17 UTC, HelyganDev commented
Thanks for the feedback @nul800sebastiaan 

I had approached this thinking that that Content Controller was only used by the Backoffice code itself. Thanks for pointing out that it is indeed a public API - which does change matters.

I might have to go back to the drawing board with this one to work out if there is an 'elegant-ish' way of handling the permission value that is set in the `FilterAllowedOutgoingContent` attribute.

If it is not possible in a way the is maintainable/sensible, I wonder if we just need to stipulate that in order to 'sort' nodes, a user requires 'browse' permission (which makes sense to me).

This could then be a documentation update, or even a message in the permission management section - just a thought.

2024-02-20 09:18 UTC, AdamPrendergast commented
Thanks for the feedback @nul800sebastiaan 

I had approached this thinking that that Content Controller was only used by the Backoffice code itself. Thanks for pointing out that it is indeed a public API - which does change matters.

I might have to go back to the drawing board with this one to work out if there is an 'elegant-ish' way of handling the permission value that is set in the `FilterAllowedOutgoingContent` attribute.

If it is not possible in a way the is maintainable/sensible, I wonder if we just need to stipulate that in order to 'sort' nodes, a user requires 'browse' permission (which makes sense to me).

This could then be a documentation update, or even a message in the permission management section - just a thought.

2025-09-25 11:51 UTC, Matthew-Wise commented
Hi @AdamPrendergast  sorry this has taken a while, as 13 is now in LTS, this wont be merged. However I have tested this in the current main and it is working, as expected!

Thanks for your effort

2025-09-25 11:51 UTC, closed without merging