Content & media url endpoints
umbraco/Umbraco-CMS pull request #15832
Opened 2024-03-05 08:45 UTC by Migaroez

### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
- New dedicated endpoints for retrieving URLs by key (e.g. for displaying picked item URLs in the content/media picker)
- Async misusage cleanup in factories

### Testing
- Create and publish some documents (preferably some in multiple cultures, don't forget to assign domains)
- Upload some temporary files and create some media from it (see example payload below)
- The following endpoints should return the relevant url info for all found documents/media by the keys you supplied `/umbraco/amanagement/api/v1/document/urls` `/umbraco/amanagement/api/v1/media/urls`

2024-03-05 09:34 UTC, Zeegaan requested changes
Had a few comments before getting to testing 😁

2024-03-05 09:34 UTC, Zeegaan commented on src/Umbraco.Cms.Api.Management/Controllers/Document/DocumentUrlController.cs
> +    [HttpGet("urls")]
No need to have `[HttpGet]` twice 😁
```suggestion
    [HttpGet("urls")]
    [MapToApiVersion("1.0")]
```

2024-03-05 09:34 UTC, Zeegaan commented on src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentUrlInfoResourceSet.cs
> +public sealed class DocumentUrlInfoResourceSet
I'm unsure about naming here, as our usual naming is either suffixed with `ViewModel` or `ResponseModel` 🤔 
Maybe we should discuss this naming with the team, just to align 😁

2024-03-05 09:34 UTC, Zeegaan commented on src/Umbraco.Cms.Api.Management/ViewModels/Media/MediaUrlInfoResourceSet.cs
> +public sealed class MediaUrlInfoResourceSet
Same as the comment in `DocumentUrlInfoResourceSet`

2024-03-05 09:34 UTC, Zeegaan commented on src/Umbraco.Cms.Api.Management/Controllers/Media/MediaUrlController.cs
> +    [ProducesResponseType(typeof(IEnumerable<MediaUrlInfoResourceSet>), StatusCodes.Status200OK)]
```suggestion
    [HttpGet("urls")]
    [MapToApiVersion("1.0")]
    [ProducesResponseType(typeof(IEnumerable<MediaUrlInfoResourceSet>), StatusCodes.Status200OK)]
```

2024-04-10 12:51 UTC, Zeegaan approved these changes
@Migaroez I changed the naming on the resourcesets, please confirm these are the correct names, then we are ready to merge 😁

2024-04-11 07:10 UTC, Migaroez commented
I am happy with the rename. Merging

2024-04-11 07:10 UTC, merged