V14 QA Added acceptance tests for Members and Member Group
umbraco/Umbraco-CMS pull request #16074
Opened 2024-04-17 06:28 UTC by nhudinh0309

2024-05-30 13:40 UTC, andr317c requested changes
Had some comments

2024-05-30 13:40 UTC, andr317c commented on tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/Members.spec.ts
> +
```suggestion
```

2024-05-30 13:40 UTC, andr317c commented on tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/Members.spec.ts
> +    await umbracoUi.member.goToSection(ConstantHelper.sections.members);
Could be in arrange

2024-05-30 13:40 UTC, andr317c commented on tests/Umbraco.Tests.AcceptanceTest/tests/auth.setup.ts
> +  await umbracoUi.page.route("**/*.{png,jpg,jpeg,webp}",(route) => route.abort());
Why is this added?

2024-05-31 06:24 UTC, nhudinh0309 commented on tests/Umbraco.Tests.AcceptanceTest/tests/auth.setup.ts
> +  await umbracoUi.page.route("**/*.{png,jpg,jpeg,webp}",(route) => route.abort());
It was here accidentally. Removed it.

2024-05-31 09:27 UTC, andr317c approved these changes
LGTM!

2024-06-03 08:23 UTC, merged