Combining OpenId and OfflineAccess scope
umbraco/Umbraco-CMS pull request #16220
Opened 2024-05-06 09:18 UTC by mcl-sz

When the client scope is set to "openid offline_access", the returned scope only has the "offline_access" scope. The "openid" scope and the "id_token" are missing. By combining the OpenId and OfflineAccess as return scope, the refresh_token and id_token are returned.

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description
This change checks if the OpenId and/or OfflineAccess scope is set and combines them.
To test I've used the Client app of this repro from Jeroen Breuer: https://github.com/jbreuer/UmbracoDeliveryApiAuthDemo

Change https://github.com/jbreuer/UmbracoDeliveryApiAuthDemo/blob/a799b307302f7189d7ddd69b9554ae2b24612eb4/src/Client/src/App.js#L22 to `const scope = 'openid offline_access';`

Copy the "OpenIdConnect" section in the appsettings.json to your own installation.

    The token result looks like this:
![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/18614643/b13ec0e8-d9c3-4065-a5d9-c7eb706d0c05)
    Note that the id_token is missing and the scope is set to "offline_access" only.

   After applying this PR, te result looks like this:

![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/18614643/c371fbff-b54d-4769-b590-f22764d8dc80)

2024-05-08 08:35 UTC, georgebid commented
Hey @mcl-sz, thanks a lot for your PR. Someone on the Core Collaborators team will review this soon 😄

2024-06-24 11:58 UTC, mcl-sz commented
Hi @georgebid, thx! Do you have any idea when the Core Collaborators team will review it?

2024-06-24 13:55 UTC, georgebid commented
@mcl-sz We aim to look at them within a few weeks but have been a little slower recently with the V14 upgrade, and Codegarden, but hopefully, it shouldn't be too much longer. 

We always like to test PRs that include great "steps to replicate" so if you can add any more tips on testing this one, that would be great 😄

2024-07-29 11:20 UTC, kjac requested changes
Hi @mcl-sz,

Functionally this makes good sense 👍 but the implementation can be a little cleaner.

I suggest something in the lines of:

```csharp
// "openid" and "offline_access" are the only scopes allowed for members; explicitly ensure we only add those
// NOTE: the "offline_access" scope is required to use refresh tokens
IEnumerable<string> allowedScopes = request
	.GetScopes()
	.Intersect(new[] { OpenIddictConstants.Scopes.OpenId, OpenIddictConstants.Scopes.OfflineAccess });
memberPrincipal.SetScopes(allowedScopes);
```

2024-07-29 13:32 UTC, mcl-sz commented
Hi @kjac , that is indeed a nicer and cleaner solution. I modified the commit.

2024-07-30 06:37 UTC, kjac approved these changes
Good stuff! 🚀

2024-07-30 06:38 UTC, merged