Optimize tracked references
umbraco/Umbraco-CMS pull request #16996
Opened 2024-09-03 08:48 UTC by Migaroez

### Description
This PR aims to reduce both the sql complexity and the data transfered from DB trough all the layers out to the api to improve performance.

A performance increase of about 25% percent has been noted across 2 different computers with the same test method: peak load testing with postman collections.

### Testing
You can ask me for a DB or connection to it that has a decent set of data (30k+ nodes). From this DB you should pick a random amount of node Ids and run them trough the altered document and media endpoints to see if you get the same results back as in the unmodified versions.

2024-09-09 08:12 UTC, bergmania requested changes
Breaking changes and functionality 🙈

2024-10-29 13:20 UTC, Migaroez commented on src/Umbraco.Cms.Api.Management/Controllers/Document/References/AreReferencedDocumentController.cs
> +        PagedModel<Guid> distinctByKeyItemsWithReferencedRelations = await _trackedReferencesSkipTakeService.GetPagedKeysWithDependentReferencesAsync(ids, Constants.ObjectTypes.Document, skip, take);
I think you might be misreading the code, let's have a look together tomorrow.

2024-11-06 07:57 UTC, bergmania commented
I retargeted for 15.1

2024-11-06 07:57 UTC, bergmania approved these changes

2024-11-06 09:27 UTC, merged