V15: Notification Hub
umbraco/Umbraco-CMS pull request #17776
Opened 2024-12-11 13:32 UTC by nikolajlauridsen

Creates a SignalR hub that relays server events to the backoffice frontend. 

These events are 
* Created
* Updated
* Deleted 

The events come from a single hub using a single method `notify`. Upon connecting, the user is authorized to receive certain events. This means that users with only `DocumentTreeAccess` will only see document events, and so on.

2025-01-07 13:44 UTC, Migaroez requested changes

2025-01-07 13:44 UTC, Migaroez commented on src/Umbraco.Core/ServerEvents/IEventSourceAuthorizer.cs
> +    public IEnumerable<string> AuthorizedEventSources { get; }
The code tells me that these are the eventSources for which this Authorizer should be run, not which eventSources have been authorized, might have to rethink the name if not reworked because of other comments.

2025-01-07 14:24 UTC, nikolajlauridsen commented on src/Umbraco.Cms.Api.Management/ServerEvents/ServerEventUserManager.cs
> +        foreach (IEventSourceAuthorizer authorizer in _eventSourceAuthorizerCollection)
Interesting, I honestly don't like the idea that the result of the authorized method is the eventSources that the claims principle is authorized for, this would make extending with your own custom events much more complicated, since you would have to still return the correct event sources for the "built in" events.

I'm not opposed to making the `AuthorizedEventSources` only allow a single eventSource, however this would again make it more unfriendly to extend. The idea with it being an enumerable is that you might want to authorize multiple events against a single criteria. For instance, we could use a single authorizer for all event sources that require `TreeAccessDocuments`. Now I chose to instead create an authorizer for every single event source, exactly for the reason that then if you really want to overwrite out default "AuthorizeAsync" you can remove the specific authorizer you want to replace the logic for and insert your own. 


I realise that there is some performance overhead to this, however given the use case I really don't see it having any real noticeable impact.

2025-01-07 14:25 UTC, nikolajlauridsen commented on src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/DocumentEventAuthorizer.cs
> +    protected override string Policy => AuthorizationPolicies.TreeAccessDocuments;
That's because `TreeAccessMedia` and `TreeAccessMember` does not exist 😄

2025-01-07 14:27 UTC, nikolajlauridsen commented on src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/RelationEventAuthorizer.cs
> +    protected override string Policy => AuthorizationPolicies.TreeAccessDocuments;
Should we then require both `TreeAccessDocuments` and `TreeAccessMediaOrMediaType`? Or neither? What do you suggest? :)

2025-01-07 14:29 UTC, nikolajlauridsen commented on src/Umbraco.Cms.Api.Management/ServerEvents/ServerEventHub.cs
> +        if (principal is null || userKey is null)
Good catch :)

2025-01-08 12:15 UTC, Migaroez commented on src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/RelationEventAuthorizer.cs
> +    protected override string Policy => AuthorizationPolicies.TreeAccessDocuments;
Since we don't have notifications for specific relations, as both the parent/child can be of any entity type that supports then, I think we should probably use TreeAccessDocumentsOrMediaOrMembersOrContentTypes

2025-01-09 09:03 UTC, nikolajlauridsen commented on src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/RelationEventAuthorizer.cs
> +    protected override string Policy => AuthorizationPolicies.TreeAccessDocuments;
Great point, I've updated that 😄

2025-01-09 13:06 UTC, Migaroez approved these changes

2025-01-10 08:36 UTC, merged

2025-03-15 19:28 UTC, umbracocommunity commented
This pull request has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/signalr-bellissima/1278/1