V8/bugfix/7981 limiting password length
umbraco/Umbraco-CMS pull request #8227
Opened 2020-06-03 20:33 UTC by redmorello

I've added an upper password limit to the umb-login form and also the Members password reset form in the backoffice.

Nothing added to the Membership Provider, I tried but it was not possible due to the existing provider.

2020-06-04 09:43 UTC, nul800sebastiaan commented
Thanks @redmorello! We will need to reject longer passwords on the server as well, this is where all the processing is being done and where people with malicious intent can try to overwhelm the server. We should do absolutely no hashing when the password is longer than this. Can you look into adding that as well please? 
I think that should be the same for the member membership provider? Not sure.

2020-07-22 18:47 UTC, redmorello commented
@nul800sebastiaan I haven't forgotten, just had a massive increase in workload the last few weeks. It's still on my todo list 👍

2020-09-01 07:10 UTC, redmorello commented
@nul800sebastiaan spent some time over the weekend changing the membership provider, and updating some tests.

2021-08-16 00:56 UTC, nathanwoulfe commented
@redmorello, appreciating this is a pretty old PR, it's still a beneficial change. I've left a couple of comments.

Will re-target to v8/contrib and deal with the conflicts.

2021-08-16 00:56 UTC, nathanwoulfe requested changes

2021-08-16 00:56 UTC, nathanwoulfe commented on src/Umbraco.Core/Security/MembershipProviderBase.cs
> +            var attempt = IsPasswordValid(e.Password, MinRequiredNonAlphanumericCharacters, PasswordStrengthRegularExpression, MinRequiredPasswordLength, MinRequiredPasswordLength);
Shouldn't this be MaxRequiredPasswordLength?

2021-08-16 00:56 UTC, nathanwoulfe commented on src/Umbraco.Core/Security/MembershipProviderBase.cs
> +            _maxRequiredPasswordLength = 256;
Could the default value here come from a constant? It's reused in a few places so would be safer

2021-08-16 00:56 UTC, nathanwoulfe commented on src/Umbraco.Core/Security/MembershipProviderPasswordValidator.cs
> +            var providerValidate = MembershipProviderBase.IsPasswordValid(item, Provider.MinRequiredNonAlphanumericCharacters, Provider.PasswordStrengthRegularExpression, Provider.MinRequiredPassword
Related to earlier - can this be constant?

2021-08-16 00:56 UTC, nathanwoulfe commented on src/Umbraco.Tests/Membership/MembershipProviderBaseTests.cs
> +            Assert.AreEqual(provider.DefaultMaxPasswordLength, 256);
Related to earlier - can this be constant?

2022-02-22 20:14 UTC, closed without merging