Update umb-property-actions toggle button
umbraco/Umbraco-CMS pull request #8565
Opened 2020-08-03 13:00 UTC by bjarnef

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8537

### Description
This PR removes the additional close button and use the toggle button, which change the text when dropdown is open/closed.

2020-08-06 10:31 UTC, bjarnef commented
@nielslyngsoe it would be great if we could ensure the js-part of the directives/components is located same place.

2020-08-24 15:31 UTC, nielslyngsoe commented
Hi @bjarnef we have two buttons to make the button go out of the paper. To provide this connected look between the dialog and the options. This PR changes that look. Any specific reason why you want to only have one button? :-)

2020-08-24 15:57 UTC, bjarnef commented
@nielslyngsoe have a look at the description in the issue :)
At the moment the close button isn't visible, but because of it exists, it requires two hits on tab key to reach the first menu action.
Furthermore the existing button already act as toggle (open/close), so no need to have the additional hidden close button.

2020-08-24 19:56 UTC, nielslyngsoe commented
@bjarnef maybe I misunderstood the description, my concern was in regards to the visual result. Its suppose to look like this:

![image](https://user-images.githubusercontent.com/6791648/91089838-6c7d1700-e654-11ea-8d26-5f691b8ae213.png)

Compared to the closed state:
![image](https://user-images.githubusercontent.com/6791648/91089868-7737ac00-e654-11ea-8137-db48a61c4a6f.png)

Notice that the button has a shadow and is white when open. In the closed state, it's greyish and has no shadow.

2020-08-24 20:22 UTC, bjarnef commented
@nielslyngsoe this PR was done in `v8/contrib` branch and before the block list was merged to this branch, so the styling may have changed. But in my tests I didn't noticed any changes visually before and after this change. See a before gif in the issue.

2020-08-26 17:05 UTC, nul800sebastiaan requested changes
@bjarnef I love it!! But yes, if you could make some style updates like @nielslyngsoe suggests then it would be perfect! 👍

2020-08-30 14:49 UTC, bjarnef commented
@nielslyngsoe @nul800sebastiaan I have adjusted this in https://github.com/umbraco/Umbraco-CMS/pull/8565/commits/a1ea42665169319b27a120d23ee408d1b18857af which clean up some styling for the extra close button on top of the existing toggle button.

**Current**

![image](https://user-images.githubusercontent.com/2919859/91662115-9913b180-eae0-11ea-8ab3-29980346a03c.png)

**Now**

![image](https://user-images.githubusercontent.com/2919859/91662164-d2e4b800-eae0-11ea-8769-27114f92be1b.png)

2020-08-30 15:09 UTC, bjarnef commented
When using tab key to navigate the toggle button and hitting enter it opens the context menu. Then subsequent tab keypress navigate the menu items and shift+tab key is navigating back.
Currently in v8.7 from first menu action and one step back closes the context menu. This is consistent with the action menu in top right corner in editing area.
However in latest changes in `v8/contrib` branch it explicit requires a enter keypress on close button or an additional step back to close the context menu.

With these changes this behaviour it similar to in v8.7.

2020-08-31 17:23 UTC, merged

2020-08-31 17:23 UTC, nul800sebastiaan commented
It's great! And it feels natural to use to me, thanks @bjarnef, great job!