Userpicker view: Change anchor element to button
umbraco/Umbraco-CMS pull request #8738
Opened 2020-08-26 21:39 UTC by BatJan

### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This is a very very samll PR changing the `<a>` tag to a `<button>` since it's not a link pointing to anywhere - Improves accessibility and screen reader announcement.

2020-08-26 21:59 UTC, abjerner commented
Hi @BatJan - I hope your doing well 😉 

Changing the `<a>` to a `<button>` indeed makes sense, and is also in line with some of your past PRs, and it looks absolutely correct when skimming through the changes. Nevertheless, I'll try to give it a spin as well to be sure, and report back here with my findings.

Thanks 👍

2020-08-27 05:14 UTC, BatJan commented
Hey @abjerner Thank you mate 😃  I'm doing good thanks - Hope you're are well too 😎

2020-08-30 19:05 UTC, abjerner commented
Thanks @BatJan. Although a but to the busy side, I'm doing good as well 😄 

The `<button>` element appears to be missing some styling to look like the `<a>` element:

1. The `<button>` element doesn't take full width, so you can't toggle the user to by clicking the empty area to the left
2. There is a bit of extra space to the left of the user name

![image](https://user-images.githubusercontent.com/3634580/91667330-169ce900-eb04-11ea-8f2d-a7bac8664e31.png)

In the screenshot above, the first item is with the `<button>` element, while the second item is with the `<a>` element (both shown with hover).

If you can fix this, it should be good to merge 😉

2020-08-30 19:06 UTC, abjerner requested changes
Aaaand I should have posted by comment as a review instead of a regular comment. If you can make the changes that I described in my previous comment, I'd be happy to merge 😉

2020-08-31 18:35 UTC, BatJan commented
@abjerner Good catch mate 👍 I've updated the styling it looks and acts like before the conversion to `<button>` 😎

2020-08-31 18:56 UTC, merged

2020-08-31 18:56 UTC, nul800sebastiaan commented
Looking good now indeed! 👍 Thanks @BatJan and @abjerner!