Userpicker: Add warning overlay when the "Remove" button is hit
umbraco/Umbraco-CMS pull request #8739
Opened 2020-08-26 23:14 UTC by BatJan

### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description

2020-08-27 06:37 UTC, nul800sebastiaan requested changes
Thanks @BatJan - to make it consistent can you change the "Yes, delete" button to "Yes, remove" instead please? It's a confusing right now to mix the terms.

2020-08-27 07:05 UTC, bjarnef commented
I recently changes the user picker property editor to use userpicker infinite editor instead or entity picker. Does the user picker property editor also shows this warning?

2020-08-27 07:56 UTC, BatJan commented
@nul800sebastiaan Yes of course - Intended to do that but missed it doh! Will have a look later 👍

2020-08-27 07:57 UTC, BatJan commented
@bjarnef Not sure - Can you share a screendump or gif of where I need to look please? 😃

2020-08-27 08:07 UTC, bjarnef commented
@BatJan I am not at my computer at the moment, but you could create an datatype instance of user picker and then use this on a new property on a document type.

2020-08-27 10:36 UTC, BatJan commented
@nul800sebastiaan The changes you requested have been pushed 👍 

@bjarnef Nope, this PR does not display it there yet since the "remove" button is not displayed in the infinite overlay but once you have picked the user. So it's in a different view that needs to be changed. I'd like to make that a separate PR at some point.

2020-08-27 11:25 UTC, bjarnef commented
@BatJan yes, I just meant both use the user picker infinite editor, but the remove function is implemented where the infine editor is used.

2020-08-27 13:59 UTC, BatJan commented
@bjarnef Yes it will require another PR :-)

2020-08-31 18:17 UTC, merged

2020-08-31 18:17 UTC, nul800sebastiaan commented
Wonderful, thanks @BatJan! 👍