Allow replacement of BPlusTree implementation, serializers, ContentData
umbraco/Umbraco-CMS pull request #8781
Opened 2020-09-01 09:07 UTC by nzdev

### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description

What?
Allow replacement of BPlusTree implementation, Serializers for BPlusTree, ContentData.

Why?
Out of the box works well but can be optimised further using alternative serialization libraries and techniques.

How:
Introduce ITransactableDictionary interface for BPlusTree.
Introduce ITransactableDictionaryFactory interface for creating ITransactableDictionary.
Inject ISerializer<IContentNodeKit> to ITransactableDictionaryFactory to allow full control over serialization to and from BPlusTree.
Introduce IContentData for ContentData.

Testing:
Replace any of the interfaces mentioned above using a composer.

2020-09-01 10:14 UTC, nzdev commented
As discussed in https://github.com/umbraco/Umbraco-CMS/pull/8365 with @Shazwazza

2020-09-24 15:20 UTC, Shazwazza requested changes
I'll need to dive deeper into this tomorrow or next week but i think it mostly makes sense. I've left one comment in there about the dictionary abstraction. Also with the latest commits to the nucache-perf branch there's some conflicts if you could fix those up when you have a chance? Cheers! :)

2020-09-24 15:20 UTC, Shazwazza commented on src/Umbraco.Web/PublishedCache/NuCache/ITransactableDictionary.cs
> +        CSharpTest.Net.Collections.IConcurrentDictionary<TKey, TValue>,
I don't think we want to use an abstraction that is part of a library that isn't part of our Core. Ideally these interfaces will move to the Core project. Can we create our own abstraction if that's necessary?

2020-09-28 05:23 UTC, Shazwazza commented
@nzdev oops, i think the latest commit(s) have pushed all netcore changes to this branch? Or something along those lines, there's a huge amount of changes now

2020-09-29 04:41 UTC, nzdev commented
Replacing with https://github.com/umbraco/Umbraco-CMS/pull/8978 due to merge mess

2020-09-29 04:41 UTC, closed without merging