Fix 8801
umbraco/Umbraco-CMS pull request #8809
Opened 2020-09-03 12:42 UTC by nielslyngsoe

fixes https://github.com/umbraco/Umbraco-CMS/issues/8801

description comes later

2020-09-04 12:32 UTC, nul800sebastiaan requested changes
Much better, I've commented out the link for now as we'll need to have somewhere to actually link to. We can add it back once we have some docs for it.

Unfortunately I can't actually delete the unsupported block.

![8809](https://user-images.githubusercontent.com/304656/92239495-69d3ba80-eebb-11ea-9baa-6d072420ec4e.gif)


The code which it points to is:

````
            function deleteBlock(block) {
                var layoutIndex = vm.layout.findIndex(function(entry) {
                    return entry.contentUdi === block.content.udi;
                });
```

Can you please see if that's fixable? 🙂

2020-09-04 12:35 UTC, nul800sebastiaan commented
whoops, commented on the wrong PR!

2020-09-07 13:36 UTC, warrenbuckley commented
Code explained to me over a call with @nielslyngsoe 
Seems OK to me now I have a bit of context to understand it

✔️ Tested with block list inside block list copying & pasting items and all UDIs are still unique

2020-09-07 13:43 UTC, warrenbuckley commented
✔️  Same with Nested Content inside Nested Content items copied & pasted correctly and still have correct unique keys for each item after node save

2020-09-07 13:43 UTC, merged