Use umb-icon in umb-node-preview
umbraco/Umbraco-CMS pull request #9072
Opened 2020-10-05 09:00 UTC by bjarnef

### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
We can use the `<umb-icon>` inside the `<umb-node-preview>` component, so we should be able to use custom SVG icons in this component as well.

2020-10-12 12:48 UTC, poornimanayar commented
Hey @bjarnef ,

How is this different from https://github.com/umbraco/Umbraco-CMS/pull/9013 ?

Poornima

2020-10-12 15:24 UTC, poornimanayar commented
Haha exactly why I asked you 😆 What can we do to achieve best of both worlds?

Poornima

2020-10-12 15:29 UTC, bjarnef commented
@poornimanayar could you have a look at your current PR and then with this change applied?
https://github.com/umbraco/Umbraco-CMS/commit/69f883625c87c3706b1b5136702edb2076a1e92a

You should be able to see a difference in icon size. Then I can close this PR.

2020-10-12 15:32 UTC, poornimanayar commented
Hi @bjarnef ,

Yes, I can apply the change to my PR and test 👍 

Poornima

2020-11-23 06:32 UTC, nathanwoulfe commented
Hey @poornimanayar / @bjarnef where are we at with this one? Is this PR still required, or does #9013 replace it?

2020-11-23 09:14 UTC, bjarnef commented
@nathanwoulfe I think the PR from @poornimanayar should be fine in https://github.com/umbraco/Umbraco-CMS/pull/9013

At the time I submitted this PR I also removed this from `umb-node-preview__icon` class:
https://github.com/umbraco/Umbraco-CMS/commit/69f883625c87c3706b1b5136702edb2076a1e92a

```
width: 25px;
min-height: 25px;
```

since the `<umb-icon>` itself handle the icon sizing and with the css above, the icons in `umb-node-preview` was smaller compared to other icons.

2020-11-23 22:51 UTC, nathanwoulfe commented
@bjarnef looks like I'd already merged @poornimanayar's PR, but will merge this too, to catch the CSS change. Given #9013 is merged, there's now a conflict in this PR - I'd resolve that for you, but git is giving me grief when trying to push to PR branches.

2020-11-23 22:51 UTC, nathanwoulfe requested changes

2020-11-23 22:51 UTC, nathanwoulfe commented on src/Umbraco.Web.UI.Client/src/views/components/umb-node-preview.html
> +        <umb-icon ng-if="icon" icon="{{icon}}" class="umb-node-preview__icon {{icon}}"></umb-icon>
The bound `{{icon}}` property in the class attribute can be removed too, it's not required.

2020-11-24 06:52 UTC, nathanwoulfe approved these changes

2020-11-24 06:53 UTC, merged