Improve GetPagedDescendants() query performance with an overload that does not do a count on each fetch
umbraco/Umbraco-CMS pull request #9284
Opened 2020-10-27 10:08 UTC by nzdev

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description
What?
Add  GetPagedDescendants overload to media/document/repositories that does not do a count. 
Replace the existing GetPagedDescendants() where the count is not used.

Why?
Existing calls to GetPagedDescendants() are inefficient. Every time you fetch a page you run a count(*) on the entire result set. This count(*) is also inefficient as it selects on unnecessary columns and may join unnecessary tables.

How to test?
Existing tests pass.

```
/// <summary>
        /// Gets a collection of <see cref="IMedia"/> objects by Parent Id
        /// </summary>
        /// <param name="id">Id of the Parent to retrieve Descendants from</param>
        /// <param name="pageIndex">Page number</param>
        /// <param name="pageSize">Page size</param>
        /// <param name="totalRecords">Total records query would return without paging</param>
        /// <param name="ordering"></param>
        /// <param name="filter"></param>
        /// <returns>An Enumerable list of <see cref="IContent"/> objects</returns>
        IEnumerable<IMedia> GetPagedDescendants(int id, long pageIndex, int pageSize,
            IQuery<IMedia> filter = null, Ordering ordering = null);
    }
```

2021-01-21 11:36 UTC, Shazwazza requested changes
I started adding comments inline but it's the same comment in all scenarios: "This code can be shared in one method which can accept a bool as to whether or not to include the count"

There's a lot of code duplication that I think can be solved with a private shared method with a bool param.

2021-01-21 11:36 UTC, Shazwazza commented on src/Umbraco.Core/Services/Implement/ContentService.cs
> +        public IEnumerable<IContent> GetPagedDescendants(int id, long pageIndex, int pageSize,
This code can be shared in one method which can accept a bool as to whether or not to include the count

2021-01-21 11:36 UTC, Shazwazza commented on src/Umbraco.Core/Services/Implement/ContentService.cs
> +        private IEnumerable<IContent> GetPagedLocked(IQuery<IContent> query, long pageIndex, int pageSize,
This code can be shared in one method which can accept a bool as to whether or not to include the count

2021-01-21 11:36 UTC, Shazwazza commented on src/Umbraco.Core/Services/Implement/MediaService.cs
> +        public IEnumerable<IMedia> GetPagedDescendants(int id, long pageIndex, int pageSize,
This code can be shared in one method which can accept a bool as to whether or not to include the count

2021-01-21 11:36 UTC, Shazwazza commented on src/Umbraco.Core/Services/Implement/MediaService.cs
> +        private IEnumerable<IMedia> GetPagedLocked(IQuery<IMedia> query, long pageIndex, int pageSize,
This code can be shared in one method which can accept a bool as to whether or not to include the count

2021-01-21 11:36 UTC, Shazwazza commented on src/Umbraco.Core/Persistence/Repositories/Implement/MemberRepository.cs
> +        public override IEnumerable<IMember> GetPage(IQuery<IMember> query, long pageIndex, int pageSize, Ordering ordering, IQuery<IMember> filter = null)
This code can be shared in one method which can accept a bool as to whether or not to include the count

2021-02-08 02:38 UTC, nzdev commented on src/Umbraco.Core/Persistence/Repositories/Implement/ContentRepositoryBase.cs
> +
This does not generate a count query

2021-02-08 02:38 UTC, nzdev commented on src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs
> +                // figure out how the "name" field is going to look like - so we can look for it
This does not generate a count query

2021-09-22 01:43 UTC, closed without merging