Update da.xml
umbraco/Umbraco-CMS pull request #9660
Opened 2021-01-15 12:12 UTC by thomashdk

Found som missing translations

### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description

2021-01-15 12:24 UTC, abjerner commented
Thanks @thomashdk and congrats with your first contribution 👍 

Do you by any chance have an example of a context in which these labels are used? That would make teasting a bit easier for me.

2021-01-15 12:29 UTC, thomashdk commented
Hey ! Thanks 

Finally took time to find out how to do it... :D

My user is set to **Danish**

And when I will "Save and Publish" Or Just "Save" and node the text will appear.

![image](https://user-images.githubusercontent.com/6445636/104727376-84edeb00-5735-11eb-9886-603e90a8d4d0.png)

I will of course in the future be better to remember to write how to reproduce an error :)

2021-01-15 13:18 UTC, abjerner requested changes
Great. I've highlighted some minor adjustments. If you can make those, I'd be happy to merge 😉

2021-01-15 13:18 UTC, abjerner commented on src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
> +    <key alias="variantsToPublish">Hvilke varianter vil du publicere?</key>
The other Danish labels in the say context says _udgive_, so could you use that as well here?

```suggestion
    <key alias="variantsToPublish">Hvilke varianter vil du udgive?</key>

```

2021-01-15 13:18 UTC, abjerner commented on src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
> +    <key alias="variantsToSave">Vælg hvilke varianter der skal gemmes.</key>
Could you add a comma here?
```suggestion
    <key alias="variantsToSave">Vælg hvilke varianter, der skal gemmes.</key>

```

2021-01-21 18:02 UTC, abjerner commented on src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
> +    <key alias="variantsToSave">Vælg hvilke varianter der skal gemmes.</key>
@thomashdk can you make this change as well? Then it should be ready to merge.

2021-01-26 20:02 UTC, abjerner approved these changes

2021-01-26 20:03 UTC, merged

2021-01-26 20:12 UTC, abjerner commented
Hey @thomashdk. I didn't hear back from you, so I went ahead and added the change that I had suggested, and merged the entire PR into `v8/contrib`. Then the translations should hopefully make it's way to the next Umbraco release 🎉 👍 

Do you by any chance have a profile on [Our Umbraco](https://our.umbraco.com/)? As a token of appreciation, and if you share the link to your Our profile here, we'll add a shiny contributors badge to your profile 😉

2021-02-01 09:44 UTC, thomashdk commented
Hej @abjerner  Thanks ! 

My profile is https://our.umbraco.com/members/id:271846/ :)

2021-02-20 15:56 UTC, nul800sebastiaan commented
Sorry for the delay @thomashdk and congrats with your shiny new contributor badge on Our! https://our.umbraco.com/members/id:271846/ - Thanks again! 🥇