Create explicit scope for mappers in UmbracoMapper
umbraco/Umbraco-CMS pull request #9995
Opened 2021-03-17 09:09 UTC by nikolajlauridsen

## Description

We have a lot of mappers that makes several calls to multiple services, resulting in multiple transactions. This PR wraps all calls to the mappers' Map methods in an explicit scope, making all Map operation result in a single transaction. 

I've tried to investigate potential issues and pros and cons. I was unable to find any issues, but the benefit of this change is also the downside to it, there will always be created an explicit scope, even for the mapping operations that don't require the scope, however, as far as I can tell, it's only a matter of object allocation, and therefore I think it's a beneficial trade-off.
 
Another minor downside to this is that it can be argued that this introduces more "magic". If you don't take a look at the UmbracoMapper implementation, it's not obvious that a scope is created for mapping operations, however, I don't think that this is a big deal.  

A thing worth noting is that with the current implementation when mapping with IEnumberables, a single scope will be created for all the mapping operations (line 260 in UmbracoMapper).

2021-03-17 09:19 UTC, AndyButland commented
Just a quick thought without really knowing the background - but did you consider amending the `Map` signatures to take a `bool wrapWithScope = false` (or similar)?  As seems like that would get around the two minor downsides you mention (not creating a scope if you don't need it, and avoiding the magic by opting in when you need it.

It does of course bring a downside and lose a benefit of what you've done, in that it will be up to the developer using a mapping operation to consider if and when a scope should be created, rather than it just happening automatically anyway.

2021-03-17 09:31 UTC, nikolajlauridsen commented
The problem with doing that is that then you will have to know if a specific object mapping needs a scope, and that requires that you know the implementation of the mapper itself, for instance, just picking a random place the `Map` method is used to map a `DataTypeSave` to an `IDataType`:

```c#
Current.Mapper.Map<IDataType>(dataType);
``` 
At this point, you have no way of knowing if this requires a scope without knowing the implementation of `DataTypeMapDefinition`.

I do think that it might be possible though to do something similar when registering a mapper in the `UmbracoMapper` with `Define` however the mappers are currently stored in a dictionary `ConcurrentDictionary<Type, Dictionary<Type, Action<object, object, MapperContext>>>` which would have to change to support this I think, so it could potentially end up in a larger rework of the `UmbracoMapper`

2021-04-07 07:01 UTC, Shazwazza requested changes
Nice and simple! Had one comment in there. I also double checked that it is correct, creating a Scope with the provider just allocates an instance and it doesn't automatically create any database instances or start any transactions, that is all done lazily only if/when the Database property of a Scope is accessed so the downside is minimal.

2021-04-07 07:02 UTC, Shazwazza commented
@nikolajlauridsen  Once that is fixed up feel free to merge. But we'll need to check with @nul800sebastiaan or someone what version this should be tagged in.

2021-04-07 07:25 UTC, nul800sebastiaan commented
We just closed 8.13 yesterday, I checked if I could merge this but I saw there was some outstanding questions, 8.14 it is!

2021-04-07 11:57 UTC, nikolajlauridsen commented on src/Umbraco.Core/Mapping/UmbracoMapper.cs
> +        public UmbracoMapper(MapDefinitionCollection profiles, IScopeProvider scopeProvider)
Ah very good point, didn't think of that, I've re-added the old constructor using `Current.ScopeProvider` and marked it as obsolete 👍

2021-04-07 12:58 UTC, merged